import type { ForumCommentVisibility, ForumPostVisibility } from '../../types/forum'

const copy = {
  en: {
    forum: 'Forum',
    forumSubtitle: 'A shared space for questions, testimonies, resources, and community updates.',
    groupForum: 'Group forum',
    groupForumSubtitle: 'Conversations for this group. Public posts can be shared beyond the group; group-only posts stay with approved members.',
    churchForum: 'Church forum',
    churchForumSubtitle: 'A shared space for church members to exchange stories, questions, resources, and updates.',
    communitySpace: 'Community space',
    groupSpace: 'Group space',
    churchSpace: 'Church community',
    feed: 'Feed',
    latestConversations: 'Latest conversations',
    conversations: 'conversations',
    activeNow: 'Active now',
    availableTopics: 'Available topics',
    chooseTopic: 'Choose a topic',
    quickShare: 'Share something with the community',
    composerHint: 'Use one language if that is all you need. The other language will fall back automatically.',
    addMedia: 'Add media',
    mediaRulePost: 'Up to 9 images or videos, max 1 video.',
    mediaRuleComment: 'One image or video.',
    mediaUploading: 'Uploading media...',
    removeMedia: 'Remove media',
    tooManyMedia: 'Too many media files selected.',
    tooManyVideos: 'Only one video is allowed.',
    commentImageOnly: 'Replies can include one image or video.',
    newPost: 'New post',
    title: 'Title',
    body: 'Body',
    category: 'Category',
    postCategory: 'Post category',
    visibility: 'Visibility',
    public: 'Public',
    membersOnly: 'Members only',
    groupOnly: 'Group only',
    publish: 'Publish',
    publishing: 'Publishing...',
    refresh: 'Refresh',
    retry: 'Retry',
    cancel: 'Cancel',
    allCategories: 'All',
    loading: 'Loading forum...',
    loadFailed: 'Unable to load the forum.',
    noPosts: 'No forum posts yet.',
    noPostsDescription: 'Start the first conversation for the community.',
    loginToPost: 'Log in to share or comment.',
    groupMemberToPost: 'Only approved group members can start or join conversations here.',
    login: 'Log in',
    replies: 'replies',
    reply: 'reply',
    replyAction: 'Reply',
    replyingTo: 'Replying to',
    cancelReply: 'Cancel reply',
    pinned: 'Pinned',
    locked: 'Locked',
    hidden: 'Hidden',
    by: 'by',
    untitled: 'Untitled post',
    emptyTitle: 'Please enter a title.',
    emptyBody: 'Please enter post content.',
    emptyComment: 'Add text, an image, or a video.',
    chooseCategory: 'Choose a category.',
    backToForum: 'Back to forum',
    comments: 'Comments',
    comment: 'Comment',
    commentVisibility: 'Comment visibility',
    groupOnlyCommentNotice: 'This comment is visible only to approved group members.',
    postComment: 'Post comment',
    postingComment: 'Posting...',
    noComments: 'No comments yet.',
    noCommentsDescription: 'Be the first to respond.',
    commentPlaceholder: 'Write a thoughtful response...',
    postNotFound: 'Post not found',
    postNotFoundDescription: 'This post may have been removed or is not visible to your account.',
    lockedHint: 'This post is locked. New comments are closed.',
    loginToComment: 'Log in to comment.',
  },
  zh: {
    forum: '论坛',
    forumSubtitle: '一个全站共享的空间，用来分享问题、见证、资源和社区消息。',
    groupForum: '小组论坛',
    groupForumSubtitle: '属于当前小组的讨论空间。公开帖子可分享给组外访客，仅小组可见的帖子只向已批准成员开放。',
    churchForum: '教会论坛',
    churchForumSubtitle: '面向全教会成员的分享空间，用来交流见证、问题、资源和近况。',
    communitySpace: '社区空间',
    groupSpace: '小组空间',
    churchSpace: '教会社区',
    feed: '动态',
    latestConversations: '最新讨论',
    conversations: '个讨论',
    activeNow: '正在更新',
    availableTopics: '可选话题',
    chooseTopic: '选择话题',
    quickShare: '和社区分享一点内容',
    composerHint: '只填一种语言也可以，切换语言时会自动 fallback 显示。',
    addMedia: '添加图片/视频',
    mediaRulePost: '最多 9 张图片或视频，最多 1 个视频。',
    mediaRuleComment: '回复最多 1 张图片或视频。',
    mediaUploading: '正在上传附件...',
    removeMedia: '移除附件',
    tooManyMedia: '选择的附件太多。',
    tooManyVideos: '最多只能包含 1 个视频。',
    commentImageOnly: '回复只能附带 1 张图片或视频。',
    newPost: '发布话题',
    title: '标题',
    body: '正文',
    category: '分类',
    postCategory: '帖子分类',
    visibility: '可见范围',
    public: '公开',
    membersOnly: '登录成员可见',
    groupOnly: '小组可见',
    publish: '发布',
    publishing: '发布中...',
    refresh: '刷新',
    retry: '重试',
    cancel: '取消',
    allCategories: '全部',
    loading: '正在加载论坛...',
    loadFailed: '暂时无法加载论坛。',
    noPosts: '还没有论坛话题。',
    noPostsDescription: '为社区发起第一个讨论吧。',
    loginToPost: '登录后可以分享和评论。',
    groupMemberToPost: '只有已批准的小组成员可以在这里发帖和评论。',
    login: '登录',
    replies: '条回复',
    reply: '条回复',
    replyAction: '回复',
    replyingTo: '正在回复',
    cancelReply: '取消回复',
    pinned: '置顶',
    locked: '已锁定',
    hidden: '已隐藏',
    by: '来自',
    untitled: '未命名话题',
    emptyTitle: '请输入标题。',
    emptyBody: '请输入正文。',
    emptyComment: '请输入文字，或添加 1 张图片/视频。',
    chooseCategory: '请选择分类。',
    backToForum: '返回论坛',
    comments: '评论',
    comment: '评论',
    commentVisibility: '评论可见范围',
    groupOnlyCommentNotice: '此评论仅对已批准的小组成员可见。',
    postComment: '发表评论',
    postingComment: '发送中...',
    noComments: '还没有评论。',
    noCommentsDescription: '成为第一个回应的人。',
    commentPlaceholder: '写下你的回应...',
    postNotFound: '没有找到话题',
    postNotFoundDescription: '这个话题可能已被移除，或你的账号暂时没有权限查看。',
    lockedHint: '这个话题已锁定，暂时不能继续评论。',
    loginToComment: '登录后可以评论。',
  },
} as const

export const forumCopy = (language: string) => (language === 'zh' ? copy.zh : copy.en)

export const visibilityLabel = (visibility: ForumPostVisibility | ForumCommentVisibility, language: string) => {
  const text = forumCopy(language)
  if (visibility === 1 || visibility === 'Public' || visibility === 'public') return text.public
  if (visibility === 3 || visibility === 'GroupOnly' || visibility === 'groupOnly') return text.groupOnly
  return text.membersOnly
}
