// <auto-generated />
using System;
using Alife.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Alife.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AlifeDbContext))]
    [Migration("20260610092425_AddNotificationReadUtc")]
    partial class AddNotificationReadUtc
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Alife.Domain.Entities.EventEnrollment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_utc");

                    b.Property<string>("EnrollmentJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("enrollment_json");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("event_id");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("group_id");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("member_id");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_utc");

                    b.HasKey("Id")
                        .HasName("pk_event_enrollments");

                    b.HasIndex("MemberId")
                        .HasDatabaseName("ix_event_enrollments_member_id");

                    b.HasIndex("EventId", "MemberId")
                        .IsUnique()
                        .HasDatabaseName("ix_event_enrollments_event_id_member_id");

                    b.HasIndex("GroupId", "UpdatedUtc")
                        .HasDatabaseName("ix_event_enrollments_group_id_updated_utc");

                    b.ToTable("event_enrollments", (string)null);
                });

            modelBuilder.Entity("Alife.Domain.Entities.EventReview", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_utc");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("event_id");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("group_id");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("member_id");

                    b.Property<string>("ReviewJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("review_json");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_utc");

                    b.HasKey("Id")
                        .HasName("pk_event_reviews");

                    b.HasIndex("MemberId")
                        .HasDatabaseName("ix_event_reviews_member_id");

                    b.HasIndex("EventId", "MemberId")
                        .HasDatabaseName("ix_event_reviews_event_id_member_id");

                    b.HasIndex("GroupId", "UpdatedUtc")
                        .HasDatabaseName("ix_event_reviews_group_id_updated_utc");

                    b.ToTable("event_reviews", (string)null);
                });

            modelBuilder.Entity("Alife.Domain.Entities.Group", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<int>("AccessType")
                        .HasColumnType("int")
                        .HasColumnName("access_type");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_utc");

                    b.Property<string>("DescriptionJson")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description_json");

                    b.Property<bool>("IsChurch")
                        .HasColumnType("bit")
                        .HasColumnName("is_church");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("bit")
                        .HasColumnName("is_closed");

                    b.Property<string>("NameJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name_json");

                    b.Property<Guid?>("ParentGroupId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("parent_group_id");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_utc");

                    b.HasKey("Id")
                        .HasName("pk_groups");

                    b.HasIndex("ParentGroupId", "UpdatedUtc")
                        .HasDatabaseName("ix_groups_parent_group_id_updated_utc");

                    b.ToTable("groups", (string)null);
                });

            modelBuilder.Entity("Alife.Domain.Entities.GroupEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("CreatedByMemberId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("created_by_member_id");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_utc");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("end_date");

                    b.Property<string>("EventDataJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("event_data_json");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("group_id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("start_date");

                    b.Property<string>("TitleEn")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("title_en");

                    b.Property<string>("TitleZh")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("title_zh");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_utc");

                    b.HasKey("Id")
                        .HasName("pk_group_events");

                    b.HasIndex("CreatedByMemberId")
                        .HasDatabaseName("ix_group_events_created_by_member_id");

                    b.HasIndex("GroupId", "UpdatedUtc")
                        .HasDatabaseName("ix_group_events_group_id_updated_utc");

                    b.ToTable("group_events", (string)null);
                });

            modelBuilder.Entity("Alife.Domain.Entities.GroupMembership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_utc");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("group_id");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("member_id");

                    b.Property<int>("Role")
                        .HasColumnType("int")
                        .HasColumnName("role");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_utc");

                    b.HasKey("Id")
                        .HasName("pk_group_memberships");

                    b.HasIndex("GroupId", "MemberId")
                        .IsUnique()
                        .HasDatabaseName("ix_group_memberships_group_id_member_id")
                        .HasFilter("[status] = 2");

                    b.HasIndex("GroupId", "Role")
                        .IsUnique()
                        .HasDatabaseName("ix_group_memberships_group_id_role")
                        .HasFilter("[status] = 2 AND [role] = 2");

                    b.HasIndex("GroupId", "UpdatedUtc")
                        .HasDatabaseName("ix_group_memberships_group_id_updated_utc");

                    b.HasIndex("MemberId", "UpdatedUtc")
                        .HasDatabaseName("ix_group_memberships_member_id_updated_utc");

                    b.ToTable("group_memberships", (string)null);
                });

            modelBuilder.Entity("Alife.Domain.Entities.Link", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("image_url");

                    b.Property<Guid>("OwnerSectionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("owner_section_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int")
                        .HasColumnName("sort_order");

                    b.Property<Guid?>("TargetGroupId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("target_group_id");

                    b.Property<Guid?>("TargetPageId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("target_page_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("title");

                    b.Property<int>("Type")
                        .HasColumnType("int")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_links");

                    b.HasIndex("OwnerSectionId")
                        .HasDatabaseName("ix_links_owner_section_id");

                    b.ToTable("links", (string)null);
                });

            modelBuilder.Entity("Alife.Domain.Entities.Member", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<int?>("Age")
                        .HasColumnType("int")
                        .HasColumnName("age");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_utc");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("email");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit")
                        .HasColumnName("is_admin");

                    b.Property<bool>("IsRegistered")
                        .HasColumnType("bit")
                        .HasColumnName("is_registered");

                    b.Property<string>("Language")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)")
                        .HasDefaultValue("zh")
                        .HasColumnName("language");

                    b.Property<string>("LineUID")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("line_uid");

                    b.Property<string>("PhoneE164")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("phone_e164");

                    b.Property<DateTime?>("PhoneVerifiedUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("phone_verified_utc");

                    b.Property<string>("Sex")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("sex");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_utc");

                    b.HasKey("Id")
                        .HasName("pk_members");

                    b.HasIndex("LineUID")
                        .IsUnique()
                        .HasDatabaseName("ix_members_line_uid")
                        .HasFilter("[line_uid] IS NOT NULL AND [is_registered] = 1");

                    b.HasIndex("PhoneE164")
                        .IsUnique()
                        .HasDatabaseName("ix_members_phone_e164")
                        .HasFilter("[phone_e164] IS NOT NULL AND [is_registered] = 1");

                    b.HasIndex("UpdatedUtc")
                        .HasDatabaseName("ix_members_updated_utc");

                    b.ToTable("members", (string)null);
                });

            modelBuilder.Entity("Alife.Domain.Entities.NotificationMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("ActionDataJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("action_data_json");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("action_type");

                    b.Property<Guid>("CreatedByMemberId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("created_by_member_id");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_utc");

                    b.Property<Guid?>("EventId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("event_id");

                    b.Property<Guid?>("GroupId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("group_id");

                    b.Property<DateTime>("OccurredUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("occurred_utc");

                    b.Property<DateTime?>("ReadUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("read_utc");

                    b.Property<Guid>("RecipientMemberId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("recipient_member_id");

                    b.Property<DateTime?>("RepliedUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("replied_utc");

                    b.Property<string>("ResponseDataJson")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("response_data_json");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_utc");

                    b.HasKey("Id")
                        .HasName("pk_notification_messages");

                    b.HasIndex("CreatedByMemberId")
                        .HasDatabaseName("ix_notification_messages_created_by_member_id");

                    b.HasIndex("EventId")
                        .HasDatabaseName("ix_notification_messages_event_id");

                    b.HasIndex("GroupId", "UpdatedUtc")
                        .HasDatabaseName("ix_notification_messages_group_id_updated_utc");

                    b.HasIndex("RecipientMemberId", "RepliedUtc", "OccurredUtc")
                        .HasDatabaseName("ix_notification_messages_recipient_member_id_replied_utc_occurred_utc");

                    b.ToTable("notification_messages", (string)null);
                });

            modelBuilder.Entity("Alife.Domain.Entities.Page", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("CreatedByMemberId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("created_by_member_id");

                    b.Property<string>("DescriptionJson")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description_json");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<Guid?>("OwnerGroupId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("owner_group_id");

                    b.Property<int>("Scope")
                        .HasColumnType("int")
                        .HasColumnName("scope");

                    b.Property<string>("TagsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("tags_json");

                    b.Property<string>("TitleDisplayStyle")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("title_display_style");

                    b.Property<string>("TitleJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("title_json");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_utc");

                    b.Property<int>("Visibility")
                        .HasColumnType("int")
                        .HasColumnName("visibility");

                    b.HasKey("Id")
                        .HasName("pk_pages");

                    b.HasIndex("CreatedByMemberId")
                        .HasDatabaseName("ix_pages_created_by_member_id");

                    b.HasIndex("OwnerGroupId")
                        .HasDatabaseName("ix_pages_owner_group_id");

                    b.HasIndex("Scope", "OwnerGroupId", "UpdatedUtc")
                        .HasDatabaseName("ix_pages_scope_owner_group_id_updated_utc");

                    b.ToTable("pages", (string)null);
                });

            modelBuilder.Entity("Alife.Domain.Entities.Section", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("ContentJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("content_json");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<int>("Order")
                        .HasColumnType("int")
                        .HasColumnName("order");

                    b.Property<Guid>("PageId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("page_id");

                    b.Property<string>("StyleJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("style_json");

                    b.Property<int>("Type")
                        .HasColumnType("int")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_sections");

                    b.HasIndex("PageId")
                        .HasDatabaseName("ix_sections_page_id");

                    b.ToTable("sections", (string)null);
                });

            modelBuilder.Entity("Alife.Domain.Entities.Sermon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("PreachedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("preached_at_utc");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int")
                        .HasColumnName("sort_order");

                    b.Property<string>("SpeakerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("speaker_name");

                    b.Property<DateTime>("SyncedUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("synced_utc");

                    b.Property<string>("ThumbnailUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("thumbnail_url");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_utc");

                    b.Property<string>("VideoUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("video_url");

                    b.Property<string>("YoutubeVideoId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("youtube_video_id");

                    b.HasKey("Id")
                        .HasName("pk_sermons");

                    b.HasIndex("SortOrder")
                        .HasDatabaseName("ix_sermons_sort_order");

                    b.HasIndex("UpdatedUtc")
                        .HasDatabaseName("ix_sermons_updated_utc");

                    b.HasIndex("YoutubeVideoId")
                        .IsUnique()
                        .HasDatabaseName("ix_sermons_youtube_video_id");

                    b.ToTable("sermons", (string)null);
                });

            modelBuilder.Entity("Alife.Domain.Entities.EventEnrollment", b =>
                {
                    b.HasOne("Alife.Domain.Entities.GroupEvent", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_event_enrollments_group_events_event_id");

                    b.HasOne("Alife.Domain.Entities.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_event_enrollments_groups_group_id");

                    b.HasOne("Alife.Domain.Entities.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_event_enrollments_members_member_id");

                    b.Navigation("Event");

                    b.Navigation("Group");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("Alife.Domain.Entities.EventReview", b =>
                {
                    b.HasOne("Alife.Domain.Entities.GroupEvent", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_event_reviews_group_events_event_id");

                    b.HasOne("Alife.Domain.Entities.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_event_reviews_groups_group_id");

                    b.HasOne("Alife.Domain.Entities.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_event_reviews_members_member_id");

                    b.Navigation("Event");

                    b.Navigation("Group");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("Alife.Domain.Entities.Group", b =>
                {
                    b.HasOne("Alife.Domain.Entities.Group", "ParentGroup")
                        .WithMany("Subgroups")
                        .HasForeignKey("ParentGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_groups_groups_parent_group_id");

                    b.Navigation("ParentGroup");
                });

            modelBuilder.Entity("Alife.Domain.Entities.GroupEvent", b =>
                {
                    b.HasOne("Alife.Domain.Entities.Member", "CreatedByMember")
                        .WithMany()
                        .HasForeignKey("CreatedByMemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_group_events_members_created_by_member_id");

                    b.HasOne("Alife.Domain.Entities.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_group_events_groups_group_id");

                    b.Navigation("CreatedByMember");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("Alife.Domain.Entities.GroupMembership", b =>
                {
                    b.HasOne("Alife.Domain.Entities.Group", "Group")
                        .WithMany("Memberships")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_group_memberships_groups_group_id");

                    b.HasOne("Alife.Domain.Entities.Member", "Member")
                        .WithMany("Memberships")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_group_memberships_members_member_id");

                    b.Navigation("Group");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("Alife.Domain.Entities.Link", b =>
                {
                    b.HasOne("Alife.Domain.Entities.Section", "OwnerSection")
                        .WithMany("Links")
                        .HasForeignKey("OwnerSectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_links_sections_owner_section_id");

                    b.Navigation("OwnerSection");
                });

            modelBuilder.Entity("Alife.Domain.Entities.NotificationMessage", b =>
                {
                    b.HasOne("Alife.Domain.Entities.Member", "CreatedByMember")
                        .WithMany()
                        .HasForeignKey("CreatedByMemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_notification_messages_members_created_by_member_id");

                    b.HasOne("Alife.Domain.Entities.GroupEvent", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_notification_messages_group_events_event_id");

                    b.HasOne("Alife.Domain.Entities.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_notification_messages_groups_group_id");

                    b.HasOne("Alife.Domain.Entities.Member", "RecipientMember")
                        .WithMany()
                        .HasForeignKey("RecipientMemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_notification_messages_members_recipient_member_id");

                    b.Navigation("CreatedByMember");

                    b.Navigation("Event");

                    b.Navigation("Group");

                    b.Navigation("RecipientMember");
                });

            modelBuilder.Entity("Alife.Domain.Entities.Page", b =>
                {
                    b.HasOne("Alife.Domain.Entities.Member", "CreatedByMember")
                        .WithMany()
                        .HasForeignKey("CreatedByMemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_pages_members_created_by_member_id");

                    b.HasOne("Alife.Domain.Entities.Group", "OwnerGroup")
                        .WithMany()
                        .HasForeignKey("OwnerGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_pages_groups_owner_group_id");

                    b.Navigation("CreatedByMember");

                    b.Navigation("OwnerGroup");
                });

            modelBuilder.Entity("Alife.Domain.Entities.Section", b =>
                {
                    b.HasOne("Alife.Domain.Entities.Page", "Page")
                        .WithMany("Sections")
                        .HasForeignKey("PageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sections_pages_page_id");

                    b.Navigation("Page");
                });

            modelBuilder.Entity("Alife.Domain.Entities.Group", b =>
                {
                    b.Navigation("Memberships");

                    b.Navigation("Subgroups");
                });

            modelBuilder.Entity("Alife.Domain.Entities.Member", b =>
                {
                    b.Navigation("Memberships");
                });

            modelBuilder.Entity("Alife.Domain.Entities.Page", b =>
                {
                    b.Navigation("Sections");
                });

            modelBuilder.Entity("Alife.Domain.Entities.Section", b =>
                {
                    b.Navigation("Links");
                });
#pragma warning restore 612, 618
        }
    }
}
