// <auto-generated />
using System;
using Alife.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Alife.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AlifeDbContext))]
    [Migration("20260707100904_RetirePageScope")]
    partial class RetirePageScope
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Alife.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("action");

                    b.Property<Guid?>("ActorMemberId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("actor_member_id");

                    b.Property<string>("AfterJson")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("after_json");

                    b.Property<string>("BeforeJson")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("before_json");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("entity_type");

                    b.Property<Guid?>("EventId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("event_id");

                    b.Property<Guid?>("GroupId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("group_id");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("ip_address");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("metadata_json");

                    b.Property<DateTime>("OccurredUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("occurred_utc");

                    b.Property<Guid?>("TargetMemberId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("target_member_id");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("user_agent");

                    b.HasKey("Id")
                        .HasName("pk_audit_logs");

                    b.HasIndex("Action", "OccurredUtc")
                        .HasDatabaseName("ix_audit_logs_action_occurred_utc");

                    b.HasIndex("ActorMemberId", "OccurredUtc")
                        .HasDatabaseName("ix_audit_logs_actor_member_id_occurred_utc");

                    b.HasIndex("EventId", "OccurredUtc")
                        .HasDatabaseName("ix_audit_logs_event_id_occurred_utc");

                    b.HasIndex("GroupId", "OccurredUtc")
                        .HasDatabaseName("ix_audit_logs_group_id_occurred_utc");

                    b.HasIndex("TargetMemberId", "OccurredUtc")
                        .HasDatabaseName("ix_audit_logs_target_member_id_occurred_utc");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("Alife.Domain.Entities.EventEnrollment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_utc");

                    b.Property<string>("EnrollmentJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("enrollment_json");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("event_id");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("group_id");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("member_id");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_utc");

                    b.HasKey("Id")
                        .HasName("pk_event_enrollments");

                    b.HasIndex("MemberId")
                        .HasDatabaseName("ix_event_enrollments_member_id");

                    b.HasIndex("EventId", "MemberId")
                        .IsUnique()
                        .HasDatabaseName("ix_event_enrollments_event_id_member_id");

                    b.HasIndex("GroupId", "UpdatedUtc")
                        .HasDatabaseName("ix_event_enrollments_group_id_updated_utc");

                    b.ToTable("event_enrollments", (string)null);
                });

            modelBuilder.Entity("Alife.Domain.Entities.EventReview", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_utc");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("event_id");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("group_id");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("member_id");

                    b.Property<string>("ReviewJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("review_json");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_utc");

                    b.HasKey("Id")
                        .HasName("pk_event_reviews");

                    b.HasIndex("MemberId")
                        .HasDatabaseName("ix_event_reviews_member_id");

                    b.HasIndex("EventId", "MemberId")
                        .HasDatabaseName("ix_event_reviews_event_id_member_id");

                    b.HasIndex("GroupId", "UpdatedUtc")
                        .HasDatabaseName("ix_event_reviews_group_id_updated_utc");

                    b.ToTable("event_reviews", (string)null);
                });

            modelBuilder.Entity("Alife.Domain.Entities.FileAsset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("BucketName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("bucket_name");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)")
                        .HasColumnName("content_type");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_utc");

                    b.Property<DateTime?>("DeletedUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleted_utc");

                    b.Property<string>("ETag")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("e_tag");

                    b.Property<Guid?>("GroupId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("group_id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<string>("ObjectKey")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)")
                        .HasColumnName("object_key");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)")
                        .HasColumnName("original_file_name");

                    b.Property<Guid?>("OwnerMemberId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("owner_member_id");

                    b.Property<string>("PublicUrl")
                        .HasMaxLength(1200)
                        .HasColumnType("nvarchar(1200)")
                        .HasColumnName("public_url");

                    b.Property<int>("Purpose")
                        .HasColumnType("int")
                        .HasColumnName("purpose");

                    b.Property<Guid?>("RelatedEntityId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("related_entity_id");

                    b.Property<string>("RelatedEntityType")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("related_entity_type");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<string>("StorageProvider")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("storage_provider");

                    b.Property<Guid?>("StorageProviderId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("storage_provider_id");

                    b.Property<string>("StoredFileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)")
                        .HasColumnName("stored_file_name");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_utc");

                    b.Property<DateTime>("UploadedUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("uploaded_utc");

                    b.Property<int>("Visibility")
                        .HasColumnType("int")
                        .HasColumnName("visibility");

                    b.HasKey("Id")
                        .HasName("pk_file_assets");

                    b.HasIndex("StorageProviderId")
                        .HasDatabaseName("ix_file_assets_storage_provider_id");

                    b.HasIndex("OwnerMemberId", "UploadedUtc")
                        .HasDatabaseName("ix_file_assets_owner_member_id_uploaded_utc");

                    b.HasIndex("RelatedEntityType", "RelatedEntityId")
                        .HasDatabaseName("ix_file_assets_related_entity_type_related_entity_id");

                    b.HasIndex("GroupId", "Visibility", "UploadedUtc")
                        .HasDatabaseName("ix_file_assets_group_id_visibility_uploaded_utc");

                    b.HasIndex("StorageProvider", "BucketName", "ObjectKey")
                        .IsUnique()
                        .HasDatabaseName("ix_file_assets_storage_provider_bucket_name_object_key")
                        .HasFilter("[is_deleted] = 0");

                    b.ToTable("file_assets", (string)null);
                });

            modelBuilder.Entity("Alife.Domain.Entities.FileStorageProvider", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("BucketName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("bucket_name");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_utc");

                    b.Property<string>("DisplayNameJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("display_name_json");

                    b.Property<string>("Endpoint")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("endpoint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit")
                        .HasColumnName("is_default");

                    b.Property<int>("Kind")
                        .HasColumnType("int")
                        .HasColumnName("kind");

                    b.Property<string>("PrivateBaseUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("private_base_url");

                    b.Property<string>("PrivatePathPrefix")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("private_path_prefix");

                    b.Property<string>("PublicBaseUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("public_base_url");

                    b.Property<string>("PublicPathPrefix")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("public_path_prefix");

                    b.Property<string>("Region")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("region");

                    b.Property<bool>("SupportsPublicUrl")
                        .HasColumnType("bit")
                        .HasColumnName("supports_public_url");

                    b.Property<bool>("SupportsServerSideMove")
                        .HasColumnType("bit")
                        .HasColumnName("supports_server_side_move");

                    b.Property<bool>("SupportsSignedRead")
                        .HasColumnType("bit")
                        .HasColumnName("supports_signed_read");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_utc");

                    b.Property<string>("UploadApiBaseUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("upload_api_base_url");

                    b.HasKey("Id")
                        .HasName("pk_file_storage_providers");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_file_storage_providers_code");

                    b.HasIndex("IsActive", "IsDefault")
                        .HasDatabaseName("ix_file_storage_providers_is_active_is_default");

                    b.ToTable("file_storage_providers", (string)null);
                });

            modelBuilder.Entity("Alife.Domain.Entities.ForumCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_utc");

                    b.Property<string>("DescriptionJson")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description_json");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit")
                        .HasColumnName("is_enabled");

                    b.Property<string>("NameJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name_json");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int")
                        .HasColumnName("sort_order");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_utc");

                    b.HasKey("Id")
                        .HasName("pk_forum_categories");

                    b.HasIndex("IsEnabled", "SortOrder")
                        .HasDatabaseName("ix_forum_categories_is_enabled_sort_order");

                    b.ToTable("forum_categories", (string)null);
                });

            modelBuilder.Entity("Alife.Domain.Entities.ForumComment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("AuthorMemberId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("author_member_id");

                    b.Property<string>("BodyJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("body_json");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_utc");

                    b.Property<DateTime?>("DeletedUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleted_utc");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("bit")
                        .HasColumnName("is_hidden");

                    b.Property<string>("MediaJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("media_json");

                    b.Property<Guid?>("ParentCommentId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("parent_comment_id");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("post_id");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_utc");

                    b.HasKey("Id")
                        .HasName("pk_forum_comments");

                    b.HasIndex("AuthorMemberId")
                        .HasDatabaseName("ix_forum_comments_author_member_id");

                    b.HasIndex("ParentCommentId")
                        .HasDatabaseName("ix_forum_comments_parent_comment_id");

                    b.HasIndex("PostId", "CreatedUtc")
                        .HasDatabaseName("ix_forum_comments_post_id_created_utc");

                    b.HasIndex("PostId", "ParentCommentId", "CreatedUtc")
                        .HasDatabaseName("ix_forum_comments_post_id_parent_comment_id_created_utc");

                    b.ToTable("forum_comments", (string)null);
                });

            modelBuilder.Entity("Alife.Domain.Entities.ForumPost", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("AuthorMemberId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("author_member_id");

                    b.Property<string>("BodyJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("body_json");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("category_id");

                    b.Property<int>("CommentCount")
                        .HasColumnType("int")
                        .HasColumnName("comment_count");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_utc");

                    b.Property<DateTime?>("DeletedUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleted_utc");

                    b.Property<Guid?>("GroupId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("group_id");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("bit")
                        .HasColumnName("is_hidden");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit")
                        .HasColumnName("is_locked");

                    b.Property<bool>("IsPinned")
                        .HasColumnType("bit")
                        .HasColumnName("is_pinned");

                    b.Property<Guid?>("LastCommentMemberId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("last_comment_member_id");

                    b.Property<DateTime?>("LastCommentUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_comment_utc");

                    b.Property<string>("MediaJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("media_json");

                    b.Property<string>("TitleJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("title_json");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_utc");

                    b.Property<int>("Visibility")
                        .HasColumnType("int")
                        .HasColumnName("visibility");

                    b.HasKey("Id")
                        .HasName("pk_forum_posts");

                    b.HasIndex("AuthorMemberId")
                        .HasDatabaseName("ix_forum_posts_author_member_id");

                    b.HasIndex("LastCommentMemberId")
                        .HasDatabaseName("ix_forum_posts_last_comment_member_id");

                    b.HasIndex("GroupId", "UpdatedUtc")
                        .HasDatabaseName("ix_forum_posts_group_id_updated_utc");

                    b.HasIndex("CategoryId", "Visibility", "UpdatedUtc")
                        .HasDatabaseName("ix_forum_posts_category_id_visibility_updated_utc");

                    b.HasIndex("Visibility", "IsHidden", "IsPinned", "UpdatedUtc")
                        .HasDatabaseName("ix_forum_posts_visibility_is_hidden_is_pinned_updated_utc");

                    b.ToTable("forum_posts", (string)null);
                });

            modelBuilder.Entity("Alife.Domain.Entities.Group", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<int>("AccessType")
                        .HasColumnType("int")
                        .HasColumnName("access_type");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_utc");

                    b.Property<string>("DescriptionJson")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description_json");

                    b.Property<bool>("IsChurch")
                        .HasColumnType("bit")
                        .HasColumnName("is_church");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("bit")
                        .HasColumnName("is_closed");

                    b.Property<string>("NameJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name_json");

                    b.Property<Guid?>("ParentGroupId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("parent_group_id");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_utc");

                    b.HasKey("Id")
                        .HasName("pk_groups");

                    b.HasIndex("ParentGroupId", "UpdatedUtc")
                        .HasDatabaseName("ix_groups_parent_group_id_updated_utc");

                    b.ToTable("groups", (string)null);
                });

            modelBuilder.Entity("Alife.Domain.Entities.GroupEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("CreatedByMemberId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("created_by_member_id");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_utc");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("end_date");

                    b.Property<string>("EventDataJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("event_data_json");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("group_id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("start_date");

                    b.Property<string>("TitleEn")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("title_en");

                    b.Property<string>("TitleZh")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("title_zh");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_utc");

                    b.HasKey("Id")
                        .HasName("pk_group_events");

                    b.HasIndex("CreatedByMemberId")
                        .HasDatabaseName("ix_group_events_created_by_member_id");

                    b.HasIndex("GroupId", "UpdatedUtc")
                        .HasDatabaseName("ix_group_events_group_id_updated_utc");

                    b.ToTable("group_events", (string)null);
                });

            modelBuilder.Entity("Alife.Domain.Entities.GroupMembership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_utc");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("group_id");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("member_id");

                    b.Property<int>("Role")
                        .HasColumnType("int")
                        .HasColumnName("role");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_utc");

                    b.HasKey("Id")
                        .HasName("pk_group_memberships");

                    b.HasIndex("GroupId", "MemberId")
                        .IsUnique()
                        .HasDatabaseName("ix_group_memberships_group_id_member_id")
                        .HasFilter("[status] = 2");

                    b.HasIndex("GroupId", "Role")
                        .IsUnique()
                        .HasDatabaseName("ix_group_memberships_group_id_role")
                        .HasFilter("[status] = 2 AND [role] = 2");

                    b.HasIndex("GroupId", "UpdatedUtc")
                        .HasDatabaseName("ix_group_memberships_group_id_updated_utc");

                    b.HasIndex("MemberId", "UpdatedUtc")
                        .HasDatabaseName("ix_group_memberships_member_id_updated_utc");

                    b.ToTable("group_memberships", (string)null);
                });

            modelBuilder.Entity("Alife.Domain.Entities.Link", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("image_url");

                    b.Property<Guid>("OwnerSectionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("owner_section_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int")
                        .HasColumnName("sort_order");

                    b.Property<Guid?>("TargetGroupId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("target_group_id");

                    b.Property<Guid?>("TargetPageId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("target_page_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("title");

                    b.Property<int>("Type")
                        .HasColumnType("int")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_links");

                    b.HasIndex("OwnerSectionId")
                        .HasDatabaseName("ix_links_owner_section_id");

                    b.ToTable("links", (string)null);
                });

            modelBuilder.Entity("Alife.Domain.Entities.Member", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<int?>("Age")
                        .HasColumnType("int")
                        .HasColumnName("age");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_utc");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("email");

                    b.Property<bool>("IsRegistered")
                        .HasColumnType("bit")
                        .HasColumnName("is_registered");

                    b.Property<string>("LineUID")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("line_uid");

                    b.Property<string>("PhoneE164")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("phone_e164");

                    b.Property<DateTime?>("PhoneVerifiedUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("phone_verified_utc");

                    b.Property<string>("Sex")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("sex");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_utc");

                    b.HasKey("Id")
                        .HasName("pk_members");

                    b.HasIndex("LineUID")
                        .IsUnique()
                        .HasDatabaseName("ix_members_line_uid")
                        .HasFilter("[line_uid] IS NOT NULL AND [is_registered] = 1");

                    b.HasIndex("PhoneE164")
                        .IsUnique()
                        .HasDatabaseName("ix_members_phone_e164")
                        .HasFilter("[phone_e164] IS NOT NULL AND [is_registered] = 1");

                    b.HasIndex("UpdatedUtc")
                        .HasDatabaseName("ix_members_updated_utc");

                    b.ToTable("members", (string)null);
                });

            modelBuilder.Entity("Alife.Domain.Entities.MemberPlatformRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid?>("AssignedByMemberId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("assigned_by_member_id");

                    b.Property<DateTime>("AssignedUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("assigned_utc");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("member_id");

                    b.Property<DateTime?>("RevokedUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("revoked_utc");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("pk_member_platform_roles");

                    b.HasIndex("AssignedByMemberId")
                        .HasDatabaseName("ix_member_platform_roles_assigned_by_member_id");

                    b.HasIndex("MemberId", "RoleId")
                        .IsUnique()
                        .HasDatabaseName("ix_member_platform_roles_member_id_role_id")
                        .HasFilter("[revoked_utc] IS NULL");

                    b.HasIndex("RoleId", "RevokedUtc")
                        .HasDatabaseName("ix_member_platform_roles_role_id_revoked_utc");

                    b.ToTable("member_platform_roles", (string)null);
                });

            modelBuilder.Entity("Alife.Domain.Entities.NotificationMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("ActionDataJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("action_data_json");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("action_type");

                    b.Property<Guid>("CreatedByMemberId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("created_by_member_id");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_utc");

                    b.Property<Guid?>("EventId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("event_id");

                    b.Property<Guid?>("GroupId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("group_id");

                    b.Property<DateTime>("OccurredUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("occurred_utc");

                    b.Property<DateTime?>("ReadUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("read_utc");

                    b.Property<Guid>("RecipientMemberId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("recipient_member_id");

                    b.Property<DateTime?>("RepliedUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("replied_utc");

                    b.Property<string>("ResponseDataJson")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("response_data_json");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_utc");

                    b.HasKey("Id")
                        .HasName("pk_notification_messages");

                    b.HasIndex("CreatedByMemberId")
                        .HasDatabaseName("ix_notification_messages_created_by_member_id");

                    b.HasIndex("EventId")
                        .HasDatabaseName("ix_notification_messages_event_id");

                    b.HasIndex("GroupId", "UpdatedUtc")
                        .HasDatabaseName("ix_notification_messages_group_id_updated_utc");

                    b.HasIndex("RecipientMemberId", "RepliedUtc", "OccurredUtc")
                        .HasDatabaseName("ix_notification_messages_recipient_member_id_replied_utc_occurred_utc");

                    b.ToTable("notification_messages", (string)null);
                });

            modelBuilder.Entity("Alife.Domain.Entities.Page", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("CreatedByMemberId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("created_by_member_id");

                    b.Property<string>("DescriptionJson")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description_json");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<Guid>("OwnerGroupId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("owner_group_id");

                    b.Property<string>("TagsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("tags_json");

                    b.Property<string>("TitleDisplayStyle")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("title_display_style");

                    b.Property<string>("TitleJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("title_json");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_utc");

                    b.Property<int>("Visibility")
                        .HasColumnType("int")
                        .HasColumnName("visibility");

                    b.HasKey("Id")
                        .HasName("pk_pages");

                    b.HasIndex("CreatedByMemberId")
                        .HasDatabaseName("ix_pages_created_by_member_id");

                    b.HasIndex("OwnerGroupId", "UpdatedUtc")
                        .HasDatabaseName("ix_pages_owner_group_id_updated_utc");

                    b.ToTable("pages", (string)null);
                });

            modelBuilder.Entity("Alife.Domain.Entities.PagePublicationReview", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("AccessNameJson")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("access_name_json");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_utc");

                    b.Property<Guid>("PageId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("page_id");

                    b.Property<string>("ReturnReason")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("return_reason");

                    b.Property<Guid?>("ReviewedByMemberId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("reviewed_by_member_id");

                    b.Property<DateTime?>("ReviewedUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("reviewed_utc");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_utc");

                    b.HasKey("Id")
                        .HasName("pk_page_publication_reviews");

                    b.HasIndex("PageId")
                        .IsUnique()
                        .HasDatabaseName("ix_page_publication_reviews_page_id");

                    b.HasIndex("ReviewedByMemberId", "ReviewedUtc")
                        .HasDatabaseName("ix_page_publication_reviews_reviewed_by_member_id_reviewed_utc");

                    b.HasIndex("Status", "UpdatedUtc")
                        .HasDatabaseName("ix_page_publication_reviews_status_updated_utc");

                    b.ToTable("page_publication_reviews", (string)null);
                });

            modelBuilder.Entity("Alife.Domain.Entities.PlatformRole", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("code");

                    b.Property<int>("Level")
                        .HasColumnType("int")
                        .HasColumnName("level");

                    b.Property<string>("NameJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name_json");

                    b.Property<string>("PermissionsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("permissions_json");

                    b.HasKey("Id")
                        .HasName("pk_platform_roles");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_platform_roles_code");

                    b.HasIndex("Level")
                        .HasDatabaseName("ix_platform_roles_level");

                    b.ToTable("platform_roles", (string)null);
                });

            modelBuilder.Entity("Alife.Domain.Entities.Section", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("ContentJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("content_json");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<int>("Order")
                        .HasColumnType("int")
                        .HasColumnName("order");

                    b.Property<Guid>("PageId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("page_id");

                    b.Property<string>("StyleJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("style_json");

                    b.Property<int>("Type")
                        .HasColumnType("int")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_sections");

                    b.HasIndex("PageId")
                        .HasDatabaseName("ix_sections_page_id");

                    b.ToTable("sections", (string)null);
                });

            modelBuilder.Entity("Alife.Domain.Entities.Sermon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("PreachedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("preached_at_utc");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int")
                        .HasColumnName("sort_order");

                    b.Property<string>("SpeakerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("speaker_name");

                    b.Property<DateTime>("SyncedUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("synced_utc");

                    b.Property<string>("ThumbnailUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("thumbnail_url");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_utc");

                    b.Property<string>("VideoUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("video_url");

                    b.Property<string>("YoutubeVideoId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("youtube_video_id");

                    b.HasKey("Id")
                        .HasName("pk_sermons");

                    b.HasIndex("SortOrder")
                        .HasDatabaseName("ix_sermons_sort_order");

                    b.HasIndex("UpdatedUtc")
                        .HasDatabaseName("ix_sermons_updated_utc");

                    b.HasIndex("YoutubeVideoId")
                        .IsUnique()
                        .HasDatabaseName("ix_sermons_youtube_video_id");

                    b.ToTable("sermons", (string)null);
                });

            modelBuilder.Entity("Alife.Domain.Entities.VisitContactRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_utc");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("email");

                    b.Property<Guid?>("HandledByMemberId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("handled_by_member_id");

                    b.Property<DateTime?>("HandledUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("handled_utc");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("ip_address");

                    b.Property<string>("Message")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("message");

                    b.Property<string>("Phone")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("phone");

                    b.Property<string>("PreferredLanguage")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("preferred_language");

                    b.Property<string>("SourcePage")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("source_page");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("status");

                    b.Property<DateTime>("SubmittedUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("submitted_utc");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_utc");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("user_agent");

                    b.HasKey("Id")
                        .HasName("pk_visit_contact_requests");

                    b.HasIndex("HandledByMemberId")
                        .HasDatabaseName("ix_visit_contact_requests_handled_by_member_id");

                    b.HasIndex("SubmittedUtc")
                        .HasDatabaseName("ix_visit_contact_requests_submitted_utc");

                    b.HasIndex("Status", "SubmittedUtc")
                        .HasDatabaseName("ix_visit_contact_requests_status_submitted_utc");

                    b.ToTable("visit_contact_requests", (string)null);
                });

            modelBuilder.Entity("Alife.Domain.Entities.AuditLog", b =>
                {
                    b.HasOne("Alife.Domain.Entities.Member", "ActorMember")
                        .WithMany()
                        .HasForeignKey("ActorMemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_audit_logs_members_actor_member_id");

                    b.HasOne("Alife.Domain.Entities.GroupEvent", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_audit_logs_group_events_event_id");

                    b.HasOne("Alife.Domain.Entities.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_audit_logs_groups_group_id");

                    b.HasOne("Alife.Domain.Entities.Member", "TargetMember")
                        .WithMany()
                        .HasForeignKey("TargetMemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_audit_logs_members_target_member_id");

                    b.Navigation("ActorMember");

                    b.Navigation("Event");

                    b.Navigation("Group");

                    b.Navigation("TargetMember");
                });

            modelBuilder.Entity("Alife.Domain.Entities.EventEnrollment", b =>
                {
                    b.HasOne("Alife.Domain.Entities.GroupEvent", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_event_enrollments_group_events_event_id");

                    b.HasOne("Alife.Domain.Entities.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_event_enrollments_groups_group_id");

                    b.HasOne("Alife.Domain.Entities.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_event_enrollments_members_member_id");

                    b.Navigation("Event");

                    b.Navigation("Group");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("Alife.Domain.Entities.EventReview", b =>
                {
                    b.HasOne("Alife.Domain.Entities.GroupEvent", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_event_reviews_group_events_event_id");

                    b.HasOne("Alife.Domain.Entities.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_event_reviews_groups_group_id");

                    b.HasOne("Alife.Domain.Entities.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_event_reviews_members_member_id");

                    b.Navigation("Event");

                    b.Navigation("Group");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("Alife.Domain.Entities.FileAsset", b =>
                {
                    b.HasOne("Alife.Domain.Entities.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_file_assets_groups_group_id");

                    b.HasOne("Alife.Domain.Entities.Member", "OwnerMember")
                        .WithMany()
                        .HasForeignKey("OwnerMemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_file_assets_members_owner_member_id");

                    b.HasOne("Alife.Domain.Entities.FileStorageProvider", "StorageProviderProfile")
                        .WithMany()
                        .HasForeignKey("StorageProviderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_file_assets_file_storage_providers_storage_provider_id");

                    b.Navigation("Group");

                    b.Navigation("OwnerMember");

                    b.Navigation("StorageProviderProfile");
                });

            modelBuilder.Entity("Alife.Domain.Entities.ForumComment", b =>
                {
                    b.HasOne("Alife.Domain.Entities.Member", "AuthorMember")
                        .WithMany("ForumComments")
                        .HasForeignKey("AuthorMemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_forum_comments_members_author_member_id");

                    b.HasOne("Alife.Domain.Entities.ForumComment", "ParentComment")
                        .WithMany("Replies")
                        .HasForeignKey("ParentCommentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_forum_comments_forum_comments_parent_comment_id");

                    b.HasOne("Alife.Domain.Entities.ForumPost", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_forum_comments_forum_posts_post_id");

                    b.Navigation("AuthorMember");

                    b.Navigation("ParentComment");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("Alife.Domain.Entities.ForumPost", b =>
                {
                    b.HasOne("Alife.Domain.Entities.Member", "AuthorMember")
                        .WithMany("ForumPosts")
                        .HasForeignKey("AuthorMemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_forum_posts_members_author_member_id");

                    b.HasOne("Alife.Domain.Entities.ForumCategory", "Category")
                        .WithMany("Posts")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_forum_posts_forum_categories_category_id");

                    b.HasOne("Alife.Domain.Entities.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_forum_posts_groups_group_id");

                    b.HasOne("Alife.Domain.Entities.Member", "LastCommentMember")
                        .WithMany()
                        .HasForeignKey("LastCommentMemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_forum_posts_members_last_comment_member_id");

                    b.Navigation("AuthorMember");

                    b.Navigation("Category");

                    b.Navigation("Group");

                    b.Navigation("LastCommentMember");
                });

            modelBuilder.Entity("Alife.Domain.Entities.Group", b =>
                {
                    b.HasOne("Alife.Domain.Entities.Group", "ParentGroup")
                        .WithMany("Subgroups")
                        .HasForeignKey("ParentGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_groups_groups_parent_group_id");

                    b.Navigation("ParentGroup");
                });

            modelBuilder.Entity("Alife.Domain.Entities.GroupEvent", b =>
                {
                    b.HasOne("Alife.Domain.Entities.Member", "CreatedByMember")
                        .WithMany()
                        .HasForeignKey("CreatedByMemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_group_events_members_created_by_member_id");

                    b.HasOne("Alife.Domain.Entities.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_group_events_groups_group_id");

                    b.Navigation("CreatedByMember");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("Alife.Domain.Entities.GroupMembership", b =>
                {
                    b.HasOne("Alife.Domain.Entities.Group", "Group")
                        .WithMany("Memberships")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_group_memberships_groups_group_id");

                    b.HasOne("Alife.Domain.Entities.Member", "Member")
                        .WithMany("Memberships")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_group_memberships_members_member_id");

                    b.Navigation("Group");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("Alife.Domain.Entities.Link", b =>
                {
                    b.HasOne("Alife.Domain.Entities.Section", "OwnerSection")
                        .WithMany("Links")
                        .HasForeignKey("OwnerSectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_links_sections_owner_section_id");

                    b.Navigation("OwnerSection");
                });

            modelBuilder.Entity("Alife.Domain.Entities.MemberPlatformRole", b =>
                {
                    b.HasOne("Alife.Domain.Entities.Member", "AssignedByMember")
                        .WithMany("AssignedPlatformRoles")
                        .HasForeignKey("AssignedByMemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_member_platform_roles_members_assigned_by_member_id");

                    b.HasOne("Alife.Domain.Entities.Member", "Member")
                        .WithMany("PlatformRoles")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_member_platform_roles_members_member_id");

                    b.HasOne("Alife.Domain.Entities.PlatformRole", "Role")
                        .WithMany("MemberRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_member_platform_roles_platform_roles_role_id");

                    b.Navigation("AssignedByMember");

                    b.Navigation("Member");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Alife.Domain.Entities.NotificationMessage", b =>
                {
                    b.HasOne("Alife.Domain.Entities.Member", "CreatedByMember")
                        .WithMany()
                        .HasForeignKey("CreatedByMemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_notification_messages_members_created_by_member_id");

                    b.HasOne("Alife.Domain.Entities.GroupEvent", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_notification_messages_group_events_event_id");

                    b.HasOne("Alife.Domain.Entities.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_notification_messages_groups_group_id");

                    b.HasOne("Alife.Domain.Entities.Member", "RecipientMember")
                        .WithMany()
                        .HasForeignKey("RecipientMemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_notification_messages_members_recipient_member_id");

                    b.Navigation("CreatedByMember");

                    b.Navigation("Event");

                    b.Navigation("Group");

                    b.Navigation("RecipientMember");
                });

            modelBuilder.Entity("Alife.Domain.Entities.Page", b =>
                {
                    b.HasOne("Alife.Domain.Entities.Member", "CreatedByMember")
                        .WithMany()
                        .HasForeignKey("CreatedByMemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_pages_members_created_by_member_id");

                    b.HasOne("Alife.Domain.Entities.Group", "OwnerGroup")
                        .WithMany()
                        .HasForeignKey("OwnerGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_pages_groups_owner_group_id");

                    b.Navigation("CreatedByMember");

                    b.Navigation("OwnerGroup");
                });

            modelBuilder.Entity("Alife.Domain.Entities.PagePublicationReview", b =>
                {
                    b.HasOne("Alife.Domain.Entities.Page", "Page")
                        .WithMany()
                        .HasForeignKey("PageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_page_publication_reviews_pages_page_id");

                    b.HasOne("Alife.Domain.Entities.Member", "ReviewedByMember")
                        .WithMany()
                        .HasForeignKey("ReviewedByMemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_page_publication_reviews_members_reviewed_by_member_id");

                    b.Navigation("Page");

                    b.Navigation("ReviewedByMember");
                });

            modelBuilder.Entity("Alife.Domain.Entities.Section", b =>
                {
                    b.HasOne("Alife.Domain.Entities.Page", "Page")
                        .WithMany("Sections")
                        .HasForeignKey("PageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sections_pages_page_id");

                    b.Navigation("Page");
                });

            modelBuilder.Entity("Alife.Domain.Entities.VisitContactRequest", b =>
                {
                    b.HasOne("Alife.Domain.Entities.Member", "HandledByMember")
                        .WithMany()
                        .HasForeignKey("HandledByMemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_visit_contact_requests_members_handled_by_member_id");

                    b.Navigation("HandledByMember");
                });

            modelBuilder.Entity("Alife.Domain.Entities.ForumCategory", b =>
                {
                    b.Navigation("Posts");
                });

            modelBuilder.Entity("Alife.Domain.Entities.ForumComment", b =>
                {
                    b.Navigation("Replies");
                });

            modelBuilder.Entity("Alife.Domain.Entities.ForumPost", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("Alife.Domain.Entities.Group", b =>
                {
                    b.Navigation("Memberships");

                    b.Navigation("Subgroups");
                });

            modelBuilder.Entity("Alife.Domain.Entities.Member", b =>
                {
                    b.Navigation("AssignedPlatformRoles");

                    b.Navigation("ForumComments");

                    b.Navigation("ForumPosts");

                    b.Navigation("Memberships");

                    b.Navigation("PlatformRoles");
                });

            modelBuilder.Entity("Alife.Domain.Entities.Page", b =>
                {
                    b.Navigation("Sections");
                });

            modelBuilder.Entity("Alife.Domain.Entities.PlatformRole", b =>
                {
                    b.Navigation("MemberRoles");
                });

            modelBuilder.Entity("Alife.Domain.Entities.Section", b =>
                {
                    b.Navigation("Links");
                });
#pragma warning restore 612, 618
        }
    }
}
