using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

#pragma warning disable CA1814 // Prefer jagged arrays over multidimensional

namespace Alife.Infrastructure.Persistence.Migrations
{
    /// <inheritdoc />
    public partial class AddEventActivityTemplateCatalog : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "event_activity_template_versions",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    code = table.Column<string>(type: "nvarchar(80)", maxLength: 80, nullable: false),
                    version = table.Column<int>(type: "int", nullable: false),
                    archetype_code = table.Column<string>(type: "nvarchar(80)", maxLength: 80, nullable: false),
                    name_en = table.Column<string>(type: "nvarchar(200)", maxLength: 200, nullable: false),
                    name_zh = table.Column<string>(type: "nvarchar(200)", maxLength: 200, nullable: false),
                    description_en = table.Column<string>(type: "nvarchar(1000)", maxLength: 1000, nullable: false),
                    description_zh = table.Column<string>(type: "nvarchar(1000)", maxLength: 1000, nullable: false),
                    icon_key = table.Column<string>(type: "nvarchar(80)", maxLength: 80, nullable: false),
                    visibility = table.Column<string>(type: "nvarchar(40)", maxLength: 40, nullable: false),
                    registration_mode = table.Column<string>(type: "nvarchar(40)", maxLength: 40, nullable: false),
                    preselected_modules_json = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    recommended_workflow_template_code = table.Column<string>(type: "nvarchar(80)", maxLength: 80, nullable: true),
                    preset_service_slots_json = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    is_active = table.Column<bool>(type: "bit", nullable: false),
                    is_current = table.Column<bool>(type: "bit", nullable: false),
                    is_system_preset = table.Column<bool>(type: "bit", nullable: false),
                    created_by_member_id = table.Column<Guid>(type: "uniqueidentifier", nullable: true),
                    created_utc = table.Column<DateTime>(type: "datetime2", nullable: false),
                    superseded_utc = table.Column<DateTime>(type: "datetime2", nullable: true),
                    concurrency_token = table.Column<Guid>(type: "uniqueidentifier", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_event_activity_template_versions", x => x.id);
                    table.ForeignKey(
                        name: "fk_event_activity_template_versions_members_created_by_member_id",
                        column: x => x.created_by_member_id,
                        principalTable: "members",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.InsertData(
                table: "event_activity_template_versions",
                columns: new[] { "id", "archetype_code", "code", "concurrency_token", "created_by_member_id", "created_utc", "description_en", "description_zh", "icon_key", "is_active", "is_current", "is_system_preset", "name_en", "name_zh", "preselected_modules_json", "preset_service_slots_json", "recommended_workflow_template_code", "registration_mode", "superseded_utc", "version", "visibility" },
                values: new object[,]
                {
                    { new Guid("0c5d8b03-b9f6-41e7-0599-a459601fd1ec"), "festival-celebration", "community-festival", new Guid("2ef8692a-5d61-e2f0-28be-7233e0596fd4"), null, new DateTime(2026, 8, 27, 0, 0, 0, 0, DateTimeKind.Utc), "A public festival with zones, live operations and hospitality.", "包含區域、現場營運與接待的公開社區節慶。", "festival", true, true, true, "Community festival", "社區節慶", "[\"PEOPLE.REGISTRATION\",\"SAFETY.RAM\",\"PROGRAM.PRODUCTION\",\"PLACE.RESOURCE\",\"FESTIVAL.OPERATIONS\",\"SERVICE.ROSTER\",\"FOOD.HOSPITALITY\",\"COMMS.FOLLOWUP\"]", "[{\"roleCode\":\"operations.commander\",\"label\":{\"en\":\"Operations commander\",\"zh\":\"\\u73FE\\u5834\\u7E3D\\u6307\\u63EE\"},\"requiredCount\":1,\"eligibilityCode\":\"approvedGroupMember\"},{\"roleCode\":\"welcome.team\",\"label\":{\"en\":\"Welcome team\",\"zh\":\"\\u63A5\\u5F85\\u5718\\u968A\"},\"requiredCount\":4,\"eligibilityCode\":\"approvedGroupMember\"},{\"roleCode\":\"stage.team\",\"label\":{\"en\":\"Stage team\",\"zh\":\"\\u821E\\u53F0\\u5718\\u968A\"},\"requiredCount\":2,\"eligibilityCode\":\"approvedGroupMember\"},{\"roleCode\":\"site.team\",\"label\":{\"en\":\"Site team\",\"zh\":\"\\u5834\\u52D9\\u5718\\u968A\"},\"requiredCount\":4,\"eligibilityCode\":\"approvedGroupMember\"},{\"roleCode\":\"hospitality.team\",\"label\":{\"en\":\"Hospitality team\",\"zh\":\"\\u9910\\u98F2\\u5718\\u968A\"},\"requiredCount\":3,\"eligibilityCode\":\"approvedGroupMember\"}]", null, "none", null, 2, "public" },
                    { new Guid("16b10dbb-e7cb-8814-1a32-353989a3cf8b"), "recurring-gathering", "bible-study-course", new Guid("d74ce8e9-f1cf-2d44-e935-58a67a766272"), null, new DateTime(2026, 8, 27, 0, 0, 0, 0, DateTimeKind.Utc), "A registered recurring course with programme and venue planning.", "需要報名、課程內容與場地規劃的定期課程。", "study", true, true, true, "Bible study/course", "查經課程", "[\"PEOPLE.REGISTRATION\",\"PROGRAM.PRODUCTION\",\"PLACE.RESOURCE\",\"SERVICE.ROSTER\",\"COMMS.FOLLOWUP\"]", "[{\"roleCode\":\"course.facilitator\",\"label\":{\"en\":\"Course facilitator\",\"zh\":\"\\u8AB2\\u7A0B\\u5E36\\u9818\"},\"requiredCount\":1,\"eligibilityCode\":\"approvedGroupMember\"},{\"roleCode\":\"registration.desk\",\"label\":{\"en\":\"Registration desk\",\"zh\":\"\\u5831\\u5230\\u8655\"},\"requiredCount\":1,\"eligibilityCode\":\"approvedGroupMember\"},{\"roleCode\":\"hospitality.host\",\"label\":{\"en\":\"Hospitality host\",\"zh\":\"\\u8336\\u9EDE\\u63A5\\u5F85\"},\"requiredCount\":1,\"eligibilityCode\":\"approvedGroupMember\"}]", null, "required", null, 2, "churchVisible" },
                    { new Guid("18d70aa5-682b-b09c-dbd6-62c11e36d563"), "simple-social", "local-outing", new Guid("632b5e69-fe7b-951a-7e15-dc8d5217131a"), null, new DateTime(2026, 8, 27, 0, 0, 0, 0, DateTimeKind.Utc), "A local day outing with registration, travel and safety planning.", "包含報名、交通與安全準備的一日外出。", "map", true, true, true, "Local outing", "一日外出", "[\"PEOPLE.REGISTRATION\",\"SAFETY.RAM\",\"MOVE.STAY\",\"SERVICE.ROSTER\",\"COMMS.FOLLOWUP\"]", "[{\"roleCode\":\"outing.lead\",\"label\":{\"en\":\"Outing lead\",\"zh\":\"\\u5916\\u51FA\\u9818\\u968A\"},\"requiredCount\":1,\"eligibilityCode\":\"approvedGroupMember\"},{\"roleCode\":\"checkin.team\",\"label\":{\"en\":\"Check-in team\",\"zh\":\"\\u5831\\u5230\\u5718\\u968A\"},\"requiredCount\":2,\"eligibilityCode\":\"approvedGroupMember\"},{\"roleCode\":\"transport.coordinator\",\"label\":{\"en\":\"Transport coordinator\",\"zh\":\"\\u4EA4\\u901A\\u5354\\u8ABF\\u54E1\"},\"requiredCount\":1,\"eligibilityCode\":\"approvedGroupMember\"}]", null, "required", null, 2, "groupVisible" },
                    { new Guid("2b8d4491-7e09-2ef0-34fe-d01a676bd67b"), "camp-retreat", "training-camp", new Guid("3e98c056-954e-9083-2c9f-999a9c1123a5"), null, new DateTime(2026, 8, 27, 0, 0, 0, 0, DateTimeKind.Utc), "A training camp with programme, venue, roster and travel coordination.", "需要節目、場地、排班與交通協作的培訓營。", "training", true, true, true, "Training camp", "培訓營", "[\"PEOPLE.REGISTRATION\",\"SAFETY.RAM\",\"PROGRAM.PRODUCTION\",\"PLACE.RESOURCE\",\"MOVE.STAY\",\"FOOD.HOSPITALITY\",\"SERVICE.ROSTER\",\"COMMS.FOLLOWUP\"]", "[{\"roleCode\":\"training.lead\",\"label\":{\"en\":\"Training lead\",\"zh\":\"\\u57F9\\u8A13\\u8CA0\\u8CAC\\u4EBA\"},\"requiredCount\":1,\"eligibilityCode\":\"approvedGroupMember\"},{\"roleCode\":\"registration.desk\",\"label\":{\"en\":\"Registration desk\",\"zh\":\"\\u5831\\u5230\\u8655\"},\"requiredCount\":2,\"eligibilityCode\":\"approvedGroupMember\"},{\"roleCode\":\"facilitator.team\",\"label\":{\"en\":\"Facilitator team\",\"zh\":\"\\u5E36\\u9818\\u5718\\u968A\"},\"requiredCount\":2,\"eligibilityCode\":\"approvedGroupMember\"},{\"roleCode\":\"hospitality.team\",\"label\":{\"en\":\"Hospitality team\",\"zh\":\"\\u9910\\u98F2\\u5718\\u968A\"},\"requiredCount\":2,\"eligibilityCode\":\"approvedGroupMember\"}]", "camp", "required", null, 2, "churchVisible" },
                    { new Guid("2e746361-5926-7397-4a33-150f76052fe7"), "recurring-gathering", "prayer-meeting", new Guid("28220f31-14e2-6e7c-9e37-06f106fcf151"), null, new DateTime(2026, 8, 27, 0, 0, 0, 0, DateTimeKind.Utc), "A recurring prayer gathering with programme and place coordination.", "包含流程與場地協作的定期禱告聚會。", "prayer", true, true, true, "Prayer meeting", "禱告會", "[\"PROGRAM.PRODUCTION\",\"PLACE.RESOURCE\",\"SERVICE.ROSTER\",\"COMMS.FOLLOWUP\"]", "[{\"roleCode\":\"prayer.lead\",\"label\":{\"en\":\"Prayer lead\",\"zh\":\"\\u79B1\\u544A\\u5E36\\u9818\"},\"requiredCount\":1,\"eligibilityCode\":\"approvedGroupMember\"},{\"roleCode\":\"welcome.team\",\"label\":{\"en\":\"Welcome team\",\"zh\":\"\\u63A5\\u5F85\\u5718\\u968A\"},\"requiredCount\":1,\"eligibilityCode\":\"approvedGroupMember\"}]", null, "none", null, 2, "groupVisible" },
                    { new Guid("301ace24-8398-3db6-bbdf-2ca24ee40774"), "simple-social", "outdoor-activity", new Guid("81852b2d-d66a-75ef-0fcb-7a3a3320cc40"), null, new DateTime(2026, 8, 27, 0, 0, 0, 0, DateTimeKind.Utc), "An outdoor activity with explicit travel and RAM review.", "需要明確交通與 RAM 檢視的戶外活動。", "outdoors", true, true, true, "Outdoor activity", "戶外活動", "[\"PEOPLE.REGISTRATION\",\"SAFETY.RAM\",\"MOVE.STAY\",\"SERVICE.ROSTER\",\"COMMS.FOLLOWUP\"]", "[{\"roleCode\":\"activity.lead\",\"label\":{\"en\":\"Activity lead\",\"zh\":\"\\u6D3B\\u52D5\\u9818\\u968A\"},\"requiredCount\":1,\"eligibilityCode\":\"approvedGroupMember\"},{\"roleCode\":\"checkin.team\",\"label\":{\"en\":\"Check-in team\",\"zh\":\"\\u5831\\u5230\\u5718\\u968A\"},\"requiredCount\":2,\"eligibilityCode\":\"approvedGroupMember\"},{\"roleCode\":\"transport.coordinator\",\"label\":{\"en\":\"Transport coordinator\",\"zh\":\"\\u4EA4\\u901A\\u5354\\u8ABF\\u54E1\"},\"requiredCount\":1,\"eligibilityCode\":\"approvedGroupMember\"}]", null, "required", null, 2, "groupVisible" },
                    { new Guid("42dd88b6-1562-6fc7-5c6a-98fe7a5b1fe5"), "simple-social", "shared-meal", new Guid("ccad4520-c318-17cb-1611-352cfedc00fb"), null, new DateTime(2026, 8, 27, 0, 0, 0, 0, DateTimeKind.Utc), "A shared meal with registration and hospitality follow-up.", "需要報名、餐飲與後續聯絡的共享聚餐。", "meal", true, true, true, "Shared meal", "聚餐・BBQ", "[\"PEOPLE.REGISTRATION\",\"FOOD.HOSPITALITY\",\"SERVICE.ROSTER\",\"COMMS.FOLLOWUP\"]", "[{\"roleCode\":\"event.host\",\"label\":{\"en\":\"Event host\",\"zh\":\"\\u6D3B\\u52D5\\u4E3B\\u6301\"},\"requiredCount\":1,\"eligibilityCode\":\"approvedGroupMember\"},{\"roleCode\":\"hospitality.lead\",\"label\":{\"en\":\"Hospitality lead\",\"zh\":\"\\u9910\\u98F2\\u8CA0\\u8CAC\\u4EBA\"},\"requiredCount\":1,\"eligibilityCode\":\"approvedGroupMember\"},{\"roleCode\":\"setup.team\",\"label\":{\"en\":\"Setup team\",\"zh\":\"\\u5834\\u5730\\u4F48\\u7F6E\\u5718\\u968A\"},\"requiredCount\":2,\"eligibilityCode\":\"approvedGroupMember\"},{\"roleCode\":\"cleanup.team\",\"label\":{\"en\":\"Cleanup team\",\"zh\":\"\\u6536\\u62FE\\u5718\\u968A\"},\"requiredCount\":2,\"eligibilityCode\":\"approvedGroupMember\"}]", null, "required", null, 2, "groupVisible" },
                    { new Guid("4b7b57cd-65c0-69e5-e9aa-c6d7954c6c67"), "camp-retreat", "church-camp", new Guid("d4e9f4f4-84ed-6c0c-1ad7-9d0756d62080"), null, new DateTime(2026, 8, 27, 0, 0, 0, 0, DateTimeKind.Utc), "A multi-session whole-church camp with operational coordination.", "需要跨模組協作的多場次全教會營會。", "camp", true, true, true, "Church camp", "全教會營會", "[\"PEOPLE.REGISTRATION\",\"SAFETY.RAM\",\"PROGRAM.PRODUCTION\",\"PLACE.RESOURCE\",\"MOVE.STAY\",\"FOOD.HOSPITALITY\",\"SERVICE.ROSTER\",\"COMMS.FOLLOWUP\"]", "[{\"roleCode\":\"camp.director\",\"label\":{\"en\":\"Camp director\",\"zh\":\"\\u71DF\\u6703\\u7E3D\\u53EC\"},\"requiredCount\":1,\"eligibilityCode\":\"approvedGroupMember\"},{\"roleCode\":\"registration.desk\",\"label\":{\"en\":\"Registration desk\",\"zh\":\"\\u5831\\u5230\\u8655\"},\"requiredCount\":2,\"eligibilityCode\":\"approvedGroupMember\"},{\"roleCode\":\"programme.team\",\"label\":{\"en\":\"Programme team\",\"zh\":\"\\u7BC0\\u76EE\\u5718\\u968A\"},\"requiredCount\":2,\"eligibilityCode\":\"approvedGroupMember\"},{\"roleCode\":\"hospitality.team\",\"label\":{\"en\":\"Hospitality team\",\"zh\":\"\\u9910\\u98F2\\u5718\\u968A\"},\"requiredCount\":2,\"eligibilityCode\":\"approvedGroupMember\"},{\"roleCode\":\"setup.team\",\"label\":{\"en\":\"Setup team\",\"zh\":\"\\u5834\\u5730\\u4F48\\u7F6E\\u5718\\u968A\"},\"requiredCount\":3,\"eligibilityCode\":\"approvedGroupMember\"}]", "camp", "required", null, 2, "churchVisible" },
                    { new Guid("5b2c8a47-42ea-02be-ea55-bbe87090bf70"), "festival-celebration", "public-outreach", new Guid("b407ef65-356e-3da6-5c21-86dddbcf1293"), null, new DateTime(2026, 8, 27, 0, 0, 0, 0, DateTimeKind.Utc), "A public outreach event with controlled outreach workflow recommendation.", "帶有受控 outreach 工作流建議的公開外展。", "outreach", true, true, true, "Public outreach", "公開外展", "[\"PEOPLE.REGISTRATION\",\"SAFETY.RAM\",\"PROGRAM.PRODUCTION\",\"PLACE.RESOURCE\",\"FESTIVAL.OPERATIONS\",\"SERVICE.ROSTER\",\"COMMS.FOLLOWUP\"]", "[{\"roleCode\":\"outreach.lead\",\"label\":{\"en\":\"Outreach lead\",\"zh\":\"\\u5916\\u5C55\\u8CA0\\u8CAC\\u4EBA\"},\"requiredCount\":1,\"eligibilityCode\":\"approvedGroupMember\"},{\"roleCode\":\"welcome.team\",\"label\":{\"en\":\"Welcome team\",\"zh\":\"\\u63A5\\u5F85\\u5718\\u968A\"},\"requiredCount\":4,\"eligibilityCode\":\"approvedGroupMember\"},{\"roleCode\":\"programme.team\",\"label\":{\"en\":\"Programme team\",\"zh\":\"\\u7BC0\\u76EE\\u5718\\u968A\"},\"requiredCount\":2,\"eligibilityCode\":\"approvedGroupMember\"},{\"roleCode\":\"site.team\",\"label\":{\"en\":\"Site team\",\"zh\":\"\\u5834\\u52D9\\u5718\\u968A\"},\"requiredCount\":4,\"eligibilityCode\":\"approvedGroupMember\"}]", "outreach", "none", null, 2, "public" },
                    { new Guid("a23304b8-e5dd-fc01-90bd-d42da5705a65"), "festival-celebration", "concert-performance", new Guid("73eea620-c319-e33a-c6be-2b6b59b7be11"), null, new DateTime(2026, 8, 27, 0, 0, 0, 0, DateTimeKind.Utc), "A public performance with registration and production operations.", "需要報名、製作與現場營運的公開演出。", "performance", true, true, true, "Concert/performance", "音樂會・演出", "[\"PEOPLE.REGISTRATION\",\"SAFETY.RAM\",\"PROGRAM.PRODUCTION\",\"PLACE.RESOURCE\",\"FESTIVAL.OPERATIONS\",\"SERVICE.ROSTER\",\"COMMS.FOLLOWUP\"]", "[{\"roleCode\":\"production.lead\",\"label\":{\"en\":\"Production lead\",\"zh\":\"\\u88FD\\u4F5C\\u8CA0\\u8CAC\\u4EBA\"},\"requiredCount\":1,\"eligibilityCode\":\"approvedGroupMember\"},{\"roleCode\":\"front.of.house\",\"label\":{\"en\":\"Front of house\",\"zh\":\"\\u524D\\u53F0\\u63A5\\u5F85\"},\"requiredCount\":4,\"eligibilityCode\":\"approvedGroupMember\"},{\"roleCode\":\"stage.team\",\"label\":{\"en\":\"Stage team\",\"zh\":\"\\u821E\\u53F0\\u5718\\u968A\"},\"requiredCount\":3,\"eligibilityCode\":\"approvedGroupMember\"},{\"roleCode\":\"av.operator\",\"label\":{\"en\":\"Audio/visual operator\",\"zh\":\"\\u97F3\\u97FF\\u5F71\\u50CF\\u64CD\\u4F5C\"},\"requiredCount\":2,\"eligibilityCode\":\"approvedGroupMember\"},{\"roleCode\":\"setup.team\",\"label\":{\"en\":\"Setup team\",\"zh\":\"\\u5834\\u5730\\u4F48\\u7F6E\\u5718\\u968A\"},\"requiredCount\":4,\"eligibilityCode\":\"approvedGroupMember\"}]", null, "required", null, 2, "public" },
                    { new Guid("ae474f4f-239f-322a-0332-8c832924ab45"), "simple-social", "fellowship-social", new Guid("1759fb74-218b-0b7e-3c6e-6812fe100fb2"), null, new DateTime(2026, 8, 27, 0, 0, 0, 0, DateTimeKind.Utc), "A low-complexity social gathering with optional attendance tracking.", "可按需要記錄出席的輕量團契聯誼。", "people", true, true, true, "Fellowship social", "團契聯誼", "[\"PEOPLE.REGISTRATION\",\"SERVICE.ROSTER\",\"COMMS.FOLLOWUP\"]", "[{\"roleCode\":\"event.host\",\"label\":{\"en\":\"Event host\",\"zh\":\"\\u6D3B\\u52D5\\u4E3B\\u6301\"},\"requiredCount\":1,\"eligibilityCode\":\"approvedGroupMember\"},{\"roleCode\":\"welcome.team\",\"label\":{\"en\":\"Welcome team\",\"zh\":\"\\u63A5\\u5F85\\u5718\\u968A\"},\"requiredCount\":2,\"eligibilityCode\":\"approvedGroupMember\"},{\"roleCode\":\"setup.team\",\"label\":{\"en\":\"Setup team\",\"zh\":\"\\u5834\\u5730\\u4F48\\u7F6E\\u5718\\u968A\"},\"requiredCount\":2,\"eligibilityCode\":\"approvedGroupMember\"}]", null, "none", null, 2, "groupVisible" },
                    { new Guid("b40de5e1-953b-ee6f-8788-04e58d9ef3e8"), "festival-celebration", "church-celebration", new Guid("50656fd0-a065-b73c-4f35-031552e84271"), null, new DateTime(2026, 8, 27, 0, 0, 0, 0, DateTimeKind.Utc), "A church celebration with registration and coordinated live operations.", "需要報名與現場協作的教會慶典。", "celebration", true, true, true, "Church celebration", "教會慶典", "[\"PEOPLE.REGISTRATION\",\"SAFETY.RAM\",\"PROGRAM.PRODUCTION\",\"PLACE.RESOURCE\",\"FESTIVAL.OPERATIONS\",\"SERVICE.ROSTER\",\"FOOD.HOSPITALITY\",\"COMMS.FOLLOWUP\"]", "[{\"roleCode\":\"celebration.lead\",\"label\":{\"en\":\"Celebration lead\",\"zh\":\"\\u6176\\u5178\\u8CA0\\u8CAC\\u4EBA\"},\"requiredCount\":1,\"eligibilityCode\":\"approvedGroupMember\"},{\"roleCode\":\"welcome.team\",\"label\":{\"en\":\"Welcome team\",\"zh\":\"\\u63A5\\u5F85\\u5718\\u968A\"},\"requiredCount\":3,\"eligibilityCode\":\"approvedGroupMember\"},{\"roleCode\":\"programme.team\",\"label\":{\"en\":\"Programme team\",\"zh\":\"\\u7BC0\\u76EE\\u5718\\u968A\"},\"requiredCount\":2,\"eligibilityCode\":\"approvedGroupMember\"},{\"roleCode\":\"setup.team\",\"label\":{\"en\":\"Setup team\",\"zh\":\"\\u5834\\u5730\\u4F48\\u7F6E\\u5718\\u968A\"},\"requiredCount\":4,\"eligibilityCode\":\"approvedGroupMember\"},{\"roleCode\":\"hospitality.team\",\"label\":{\"en\":\"Hospitality team\",\"zh\":\"\\u9910\\u98F2\\u5718\\u968A\"},\"requiredCount\":3,\"eligibilityCode\":\"approvedGroupMember\"}]", null, "required", null, 2, "churchVisible" },
                    { new Guid("e937f772-f4dd-1f0e-4813-ba46532dbb3d"), "recurring-gathering", "worship-service", new Guid("88e7abc8-5990-b6a5-3beb-976e210bf811"), null, new DateTime(2026, 8, 27, 0, 0, 0, 0, DateTimeKind.Utc), "A recurring worship service with programme, venue and roster planning.", "包含節目、場地與排班規劃的定期崇拜。", "worship", true, true, true, "Worship service", "主日聚會", "[\"PROGRAM.PRODUCTION\",\"PLACE.RESOURCE\",\"SERVICE.ROSTER\",\"COMMS.FOLLOWUP\"]", "[{\"roleCode\":\"service.lead\",\"label\":{\"en\":\"Service lead\",\"zh\":\"\\u805A\\u6703\\u4E3B\\u9818\"},\"requiredCount\":1,\"eligibilityCode\":\"approvedGroupMember\"},{\"roleCode\":\"welcome.team\",\"label\":{\"en\":\"Welcome team\",\"zh\":\"\\u63A5\\u5F85\\u5718\\u968A\"},\"requiredCount\":2,\"eligibilityCode\":\"approvedGroupMember\"},{\"roleCode\":\"worship.team\",\"label\":{\"en\":\"Worship team\",\"zh\":\"\\u656C\\u62DC\\u5718\\u968A\"},\"requiredCount\":3,\"eligibilityCode\":\"approvedGroupMember\"},{\"roleCode\":\"av.operator\",\"label\":{\"en\":\"Audio/visual operator\",\"zh\":\"\\u97F3\\u97FF\\u5F71\\u50CF\\u64CD\\u4F5C\"},\"requiredCount\":1,\"eligibilityCode\":\"approvedGroupMember\"}]", null, "none", null, 2, "churchVisible" },
                    { new Guid("ea4884f4-bce2-c92c-5131-845083ca110f"), "camp-retreat", "spiritual-retreat", new Guid("929caed9-a0a5-9a4d-a5e0-e10c32a3f6f0"), null, new DateTime(2026, 8, 27, 0, 0, 0, 0, DateTimeKind.Utc), "A retreat centred on programme, place, travel and hospitality.", "以節目、場地、交通與接待為核心的退修會。", "retreat", true, true, true, "Spiritual retreat", "靈修退修會", "[\"PEOPLE.REGISTRATION\",\"SAFETY.RAM\",\"PROGRAM.PRODUCTION\",\"PLACE.RESOURCE\",\"MOVE.STAY\",\"FOOD.HOSPITALITY\",\"SERVICE.ROSTER\",\"COMMS.FOLLOWUP\"]", "[{\"roleCode\":\"retreat.lead\",\"label\":{\"en\":\"Retreat lead\",\"zh\":\"\\u9000\\u4FEE\\u6703\\u5E36\\u9818\"},\"requiredCount\":1,\"eligibilityCode\":\"approvedGroupMember\"},{\"roleCode\":\"welcome.team\",\"label\":{\"en\":\"Welcome team\",\"zh\":\"\\u63A5\\u5F85\\u5718\\u968A\"},\"requiredCount\":2,\"eligibilityCode\":\"approvedGroupMember\"},{\"roleCode\":\"programme.team\",\"label\":{\"en\":\"Programme team\",\"zh\":\"\\u7BC0\\u76EE\\u5718\\u968A\"},\"requiredCount\":2,\"eligibilityCode\":\"approvedGroupMember\"},{\"roleCode\":\"hospitality.team\",\"label\":{\"en\":\"Hospitality team\",\"zh\":\"\\u9910\\u98F2\\u5718\\u968A\"},\"requiredCount\":2,\"eligibilityCode\":\"approvedGroupMember\"}]", "camp", "required", null, 2, "churchVisible" },
                    { new Guid("f4136549-9494-1b7f-54ce-25ccaa925534"), "recurring-gathering", "small-group-fellowship", new Guid("bddf3995-852a-070c-e52e-ac9ccd57e7e5"), null, new DateTime(2026, 8, 27, 0, 0, 0, 0, DateTimeKind.Utc), "A weekly group gathering with programme, place and follow-up.", "包含節目、場地與跟進的每週小組聚會。", "fellowship", true, true, true, "Small-group fellowship", "小組團契", "[\"PROGRAM.PRODUCTION\",\"PLACE.RESOURCE\",\"SERVICE.ROSTER\",\"COMMS.FOLLOWUP\"]", "[{\"roleCode\":\"gathering.host\",\"label\":{\"en\":\"Gathering host\",\"zh\":\"\\u805A\\u6703\\u63A5\\u5F85\"},\"requiredCount\":1,\"eligibilityCode\":\"approvedGroupMember\"},{\"roleCode\":\"discussion.facilitator\",\"label\":{\"en\":\"Discussion facilitator\",\"zh\":\"\\u8A0E\\u8AD6\\u5E36\\u9818\"},\"requiredCount\":1,\"eligibilityCode\":\"approvedGroupMember\"},{\"roleCode\":\"hospitality.host\",\"label\":{\"en\":\"Hospitality host\",\"zh\":\"\\u8336\\u9EDE\\u63A5\\u5F85\"},\"requiredCount\":1,\"eligibilityCode\":\"approvedGroupMember\"}]", null, "none", null, 2, "groupVisible" },
                    { new Guid("fb233223-3e78-9532-071a-9ec5cade1366"), "camp-retreat", "children-youth-camp", new Guid("6541a8c5-4d90-a1e9-3806-0d6e7398f002"), null, new DateTime(2026, 8, 27, 0, 0, 0, 0, DateTimeKind.Utc), "A camp preset that surfaces safeguarding for explicit policy review.", "預選兒童保護並要求明確政策檢視的營會。", "children", true, true, true, "Children/youth camp", "兒童・青少年營", "[\"PEOPLE.REGISTRATION\",\"SAFETY.RAM\",\"SAFEGUARDING.CHILD\",\"PROGRAM.PRODUCTION\",\"PLACE.RESOURCE\",\"MOVE.STAY\",\"FOOD.HOSPITALITY\",\"SERVICE.ROSTER\",\"COMMS.FOLLOWUP\"]", "[{\"roleCode\":\"camp.director\",\"label\":{\"en\":\"Camp director\",\"zh\":\"\\u71DF\\u6703\\u7E3D\\u53EC\"},\"requiredCount\":1,\"eligibilityCode\":\"approvedGroupMember\"},{\"roleCode\":\"registration.desk\",\"label\":{\"en\":\"Registration desk\",\"zh\":\"\\u5831\\u5230\\u8655\"},\"requiredCount\":2,\"eligibilityCode\":\"approvedGroupMember\"},{\"roleCode\":\"programme.team\",\"label\":{\"en\":\"Programme team\",\"zh\":\"\\u7BC0\\u76EE\\u5718\\u968A\"},\"requiredCount\":2,\"eligibilityCode\":\"approvedGroupMember\"},{\"roleCode\":\"hospitality.team\",\"label\":{\"en\":\"Hospitality team\",\"zh\":\"\\u9910\\u98F2\\u5718\\u968A\"},\"requiredCount\":2,\"eligibilityCode\":\"approvedGroupMember\"}]", "camp", "required", null, 2, "churchVisible" }
                });

            migrationBuilder.CreateIndex(
                name: "ix_event_activity_template_versions_archetype_code_is_current_is_active_name_en",
                table: "event_activity_template_versions",
                columns: new[] { "archetype_code", "is_current", "is_active", "name_en" });

            migrationBuilder.CreateIndex(
                name: "ix_event_activity_template_versions_code",
                table: "event_activity_template_versions",
                column: "code",
                unique: true,
                filter: "[is_current] = 1");

            migrationBuilder.CreateIndex(
                name: "ix_event_activity_template_versions_code_version",
                table: "event_activity_template_versions",
                columns: new[] { "code", "version" },
                unique: true);

            migrationBuilder.CreateIndex(
                name: "ix_event_activity_template_versions_created_by_member_id",
                table: "event_activity_template_versions",
                column: "created_by_member_id");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "event_activity_template_versions");
        }
    }
}
