// <auto-generated />
using Alife.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Alife.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AlifeDbContext))]
    [Migration("20260706020000_AddForumCommentReplies")]
    partial class AddForumCommentReplies
    {
    }
}
