// <auto-generated />
using System;
using Alife.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Alife.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AlifeDbContext))]
    partial class AlifeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Alife.Domain.Entities.Group", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<int>("AccessType")
                        .HasColumnType("int")
                        .HasColumnName("access_type");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_utc");

                    b.Property<bool>("IsChurch")
                        .HasColumnType("bit")
                        .HasColumnName("is_church");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("bit")
                        .HasColumnName("is_closed");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("name");

                    b.Property<Guid?>("ParentGroupId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("parent_group_id");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_utc");

                    b.HasKey("Id")
                        .HasName("pk_groups");

                    b.HasIndex("ParentGroupId")
                        .HasDatabaseName("ix_groups_parent_group_id");

                    b.ToTable("groups", (string)null);
                });

            modelBuilder.Entity("Alife.Domain.Entities.GroupMembership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_utc");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("group_id");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("member_id");

                    b.Property<int>("Role")
                        .HasColumnType("int")
                        .HasColumnName("role");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_utc");

                    b.HasKey("Id")
                        .HasName("pk_group_memberships");

                    b.HasIndex("MemberId")
                        .HasDatabaseName("ix_group_memberships_member_id");

                    b.HasIndex("GroupId", "MemberId")
                        .IsUnique()
                        .HasDatabaseName("ix_group_memberships_group_id_member_id")
                        .HasFilter("[status] = 2");

                    b.HasIndex("GroupId", "Role")
                        .IsUnique()
                        .HasDatabaseName("ix_group_memberships_group_id_role")
                        .HasFilter("[status] = 2 AND [role] = 2");

                    b.ToTable("group_memberships", (string)null);
                });

            modelBuilder.Entity("Alife.Domain.Entities.Link", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("image_url");

                    b.Property<Guid>("OwnerSectionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("owner_section_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int")
                        .HasColumnName("sort_order");

                    b.Property<Guid?>("TargetGroupId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("target_group_id");

                    b.Property<Guid?>("TargetPageId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("target_page_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("title");

                    b.Property<int>("Type")
                        .HasColumnType("int")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_links");

                    b.HasIndex("OwnerSectionId")
                        .HasDatabaseName("ix_links_owner_section_id");

                    b.ToTable("links", (string)null);
                });

            modelBuilder.Entity("Alife.Domain.Entities.Member", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<int?>("Age")
                        .HasColumnType("int")
                        .HasColumnName("age");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_utc");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("email");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit")
                        .HasColumnName("is_admin");

                    b.Property<bool>("IsRegistered")
                        .HasColumnType("bit")
                        .HasColumnName("is_registered");

                    b.Property<string>("PhoneE164")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("phone_e164");

                    b.Property<DateTime?>("PhoneVerifiedUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("phone_verified_utc");

                    b.Property<string>("Sex")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("sex");

                    b.HasKey("Id")
                        .HasName("pk_members");

                    b.HasIndex("PhoneE164")
                        .IsUnique()
                        .HasDatabaseName("ix_members_phone_e164")
                        .HasFilter("[phone_e164] IS NOT NULL AND [is_registered] = 1");

                    b.ToTable("members", (string)null);
                });

            modelBuilder.Entity("Alife.Domain.Entities.Page", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("CreatedByMemberId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("created_by_member_id");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("language");

                    b.Property<Guid?>("OwnerGroupId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("owner_group_id");

                    b.Property<int>("Scope")
                        .HasColumnType("int")
                        .HasColumnName("scope");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("slug");

                    b.Property<string>("TagsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("tags_json");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("title");

                    b.Property<string>("TitleDisplayStyle")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("title_display_style");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_utc");

                    b.Property<int>("Visibility")
                        .HasColumnType("int")
                        .HasColumnName("visibility");

                    b.HasKey("Id")
                        .HasName("pk_pages");

                    b.HasIndex("CreatedByMemberId")
                        .HasDatabaseName("ix_pages_created_by_member_id");

                    b.HasIndex("OwnerGroupId")
                        .HasDatabaseName("ix_pages_owner_group_id");

                    b.HasIndex("Scope", "OwnerGroupId", "Slug", "Language")
                        .IsUnique()
                        .HasDatabaseName("ix_pages_scope_owner_group_id_slug_language")
                        .HasFilter("[owner_group_id] IS NOT NULL");

                    b.ToTable("pages", (string)null);
                });

            modelBuilder.Entity("Alife.Domain.Entities.Section", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("ContentJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("content_json");

                    b.Property<int>("Order")
                        .HasColumnType("int")
                        .HasColumnName("order");

                    b.Property<Guid>("PageId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("page_id");

                    b.Property<string>("StyleJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("style_json");

                    b.Property<int>("Type")
                        .HasColumnType("int")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_sections");

                    b.HasIndex("PageId")
                        .HasDatabaseName("ix_sections_page_id");

                    b.ToTable("sections", (string)null);
                });

            modelBuilder.Entity("Alife.Domain.Entities.Group", b =>
                {
                    b.HasOne("Alife.Domain.Entities.Group", "ParentGroup")
                        .WithMany("Subgroups")
                        .HasForeignKey("ParentGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_groups_groups_parent_group_id");

                    b.Navigation("ParentGroup");
                });

            modelBuilder.Entity("Alife.Domain.Entities.GroupMembership", b =>
                {
                    b.HasOne("Alife.Domain.Entities.Group", "Group")
                        .WithMany("Memberships")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_group_memberships_groups_group_id");

                    b.HasOne("Alife.Domain.Entities.Member", "Member")
                        .WithMany("Memberships")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_group_memberships_members_member_id");

                    b.Navigation("Group");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("Alife.Domain.Entities.Link", b =>
                {
                    b.HasOne("Alife.Domain.Entities.Section", "OwnerSection")
                        .WithMany("Links")
                        .HasForeignKey("OwnerSectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_links_sections_owner_section_id");

                    b.Navigation("OwnerSection");
                });

            modelBuilder.Entity("Alife.Domain.Entities.Page", b =>
                {
                    b.HasOne("Alife.Domain.Entities.Member", "CreatedByMember")
                        .WithMany()
                        .HasForeignKey("CreatedByMemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_pages_members_created_by_member_id");

                    b.HasOne("Alife.Domain.Entities.Group", "OwnerGroup")
                        .WithMany()
                        .HasForeignKey("OwnerGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_pages_groups_owner_group_id");

                    b.Navigation("CreatedByMember");

                    b.Navigation("OwnerGroup");
                });

            modelBuilder.Entity("Alife.Domain.Entities.Section", b =>
                {
                    b.HasOne("Alife.Domain.Entities.Page", "Page")
                        .WithMany("Sections")
                        .HasForeignKey("PageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sections_pages_page_id");

                    b.Navigation("Page");
                });

            modelBuilder.Entity("Alife.Domain.Entities.Group", b =>
                {
                    b.Navigation("Memberships");

                    b.Navigation("Subgroups");
                });

            modelBuilder.Entity("Alife.Domain.Entities.Member", b =>
                {
                    b.Navigation("Memberships");
                });

            modelBuilder.Entity("Alife.Domain.Entities.Page", b =>
                {
                    b.Navigation("Sections");
                });

            modelBuilder.Entity("Alife.Domain.Entities.Section", b =>
                {
                    b.Navigation("Links");
                });
#pragma warning restore 612, 618
        }
    }
}
