// All application APIs are fixtures. Run against Vite; no real events are created.
const assert = require('node:assert/strict');
const { showDetailsPane, expandTranslation } = require('./helpers/eventDetailsWorkspace.cjs');
const { chromium } = require(process.env.ALIFE_PLAYWRIGHT_MODULE || 'playwright');
const os = require('node:os');
const path = require('node:path');
const base = process.env.ALIFE_BROWSER_BASE_URL || 'http://127.0.0.1:5173';
const label = (en, zh) => ({ en, zh });
const template = { code: 'shared-meal', archetypeCode: 'simple-social', version: 2, name: label('Fellowship meal', '团契聚餐'), description: label('Share a meal', '一起用餐'), iconKey: 'meal', defaults: { visibility: 'groupVisible', registrationMode: 'none', capacityUnit: 'People' }, preselectedModules: ['SERVICE.ROSTER'], presetServiceSlots: [{ roleCode: 'programme.team', label: label('Welcome team', '接待同工'), requiredCount: 2, eligibilityCode: 'approvedGroupMember' }] };
const catalogue = [{ code: 'simple-social', version: 1, name: label('Simple social', '轻松相聚'), isSeries: false, occurrenceCount: 1, hasSessions: false, hasZones: false, requiredModules: [], recommendedModules: [], conditionalModules: [], workflowTemplateRecommendations: [], activityTypes: [template] }];
const modules = [ ['SAFEGUARDING.CHILD', 'Child safeguarding', '儿童保护'], ['SAFETY.RAM', 'RAM and safety', 'RAM 与安全'], ['TEAM.WORK', 'Team and tasks', '团队与任务'], ['SERVICE.ROSTER', 'Roles and shifts', '岗位与轮班'], ['PROGRAM.PRODUCTION', 'Programme and production', '节目与制作'], ['PLACE.RESOURCE', 'Venue and resources', '场地与资源'], ['PEOPLE.REGISTRATION','Registration','邀请报名'], ['FESTIVAL.OPERATIONS','Operations','现场运营'], ['MOVE.STAY','Travel and stay','交通住宿'], ['FOOD.HOSPITALITY','Food','餐饮'], ['MONEY.FINANCE','Finance','费用'], ['COMMS.FOLLOWUP','Follow-up','跟进'] ];
const venue = { id: 'venue-1', managingGroupId: 'qa-group', name: label('Main hall', '主礼堂'), address: label('10 Main Road', '主路10号'), capacity: 50, isActive: true, eTag: '"venue-v1"' };
const relatedModules = new Set(['TEAM.WORK', 'SERVICE.ROSTER']);

(async () => {
  const browser = await chromium.launch({ headless: true, ...(process.env.ALIFE_BROWSER_EXECUTABLE ? { executablePath: process.env.ALIFE_BROWSER_EXECUTABLE } : {}) }); let lastPage = null;
  try {
    for (const language of (process.env.ALIFE_QA_LANGUAGES || 'zh,en').split(',')) for (const width of (process.env.ALIFE_QA_WIDTHS || '320,375,768,1280').split(',').map(Number)) {
      const zh = language === 'zh', t = (en, cn) => zh ? cn : en;
      const context = await browser.newContext({ viewport: { width, height: 900 }, reducedMotion: 'reduce', serviceWorkers: 'block' });
      await context.addInitScript(language => localStorage.setItem('alife.language', language), language);
      const page = await context.newPage(); lastPage = page; page.setDefaultTimeout(30000);
      const errors = [], creates = []; let venueLoads = 0, composeLoads = 0;
      page.on('pageerror', e => errors.push(e.message));
      await context.route('**/api/**', async route => {
        const request = route.request(), pathname = new URL(request.url()).pathname;
        let data = [], status = 200;
        if (pathname === '/api/me') data = { id: 'qa', displayName: 'QA Leader', isGuest: false, isRegistered: true, platformRole: 'superadmin', permissions: ['admin.access'], memberships: [] };
        else if (pathname === '/api/event-archetypes') data = catalogue;
        else if (pathname === '/api/events/ram-authoring/context') data = { policy: null, sourceVersion: 'new', title: label('', '') };
        else if (pathname === '/api/events/ram-authoring/check') data = { draft: JSON.parse(request.postDataJSON().ramDataJson), residualLevel: 'Incomplete', issues: [{ field: 'ram.participants', message: label('Verify participant count', '请核实参与人数') }], policy: null };
        else if (pathname === '/api/events/ram-assistance') {
          const input = request.postDataJSON();
          assert.deepEqual(Object.keys(input).sort(), ['activityType', 'brief', 'category', 'groupId', 'language', 'mode', 'selectedText', 'sourceVersion']);
          assert.equal(input.groupId, 'qa-group'); assert.equal(input.sourceVersion, 'new');
          assert.equal(input.mode, 'draft'); assert.ok(!JSON.stringify(input).includes('Private RAM hazard'));
          assert.equal(creates.length, 0);
          data = { sourceVersion: 'new', suggestions: { controlMeasures: t('Keep the walkway clear', '保持通道畅通') }, questions: [] };
        }
        else if (pathname.endsWith('/venues')) { venueLoads++; data = { managingGroupId: 'qa-group', canManage: true, venues: [venue] }; }
        else if (pathname.endsWith('/compose')) {
          composeLoads++; const input = request.postDataJSON();
          data = { schemaVersion: '1.1.0', proposalHash: JSON.stringify(input.humanSelections), baselineETag: '"plan-new"', facts: { items: [], sourceHash: 'facts' }, roleRequirements: [], workflowContributions: [], navigation: [], warnings: [], readiness: { status: 'notReady', blockers: [], warnings: [] },
            moduleDecisions: modules.map(([moduleCode, en, cn]) => ({ moduleCode, label: label(en, cn), status: moduleCode === 'TEAM.WORK' ? 'required' : (input.humanSelections.find(x => x.moduleCode === moduleCode)?.selected ?? moduleCode === 'SERVICE.ROSTER') ? 'selected' : 'inactive', reasonCodes: [], dependencies: [], dataClasses: [], integrationKey: '', surfaceKey: '', navigationOrder: 1 })) };
        } else if (pathname.endsWith('/events') && request.method() === 'POST') {
          const body = request.postDataJSON(); assert.equal(JSON.parse(body.ramDataJson).hazards[0].hazard.en, 'Private RAM hazard');
          const { ramDataJson, ...publicBody } = body; assert.ok(!JSON.stringify(publicBody).includes('Private RAM hazard'));
          creates.push({ body, key: request.headers()['idempotency-key'] });
          status = creates.length === 1 ? 409 : 503;
          data = { message: creates.length === 1 ? 'A venue conflicts with another booking.' : 'Temporary failure for retry test.' };
        }
        await route.fulfill({ status, json: data });
      });
      const next = () => page.getByRole('navigation', { name: t('Event preparation flow', '活动筹备流程') }).getByRole('button').filter({ hasText: t('Create', '确认创建') }).click();
      const region = (en, cn) => page.getByRole('region', { name: t(en, cn), exact: true });
      const fillText = async (root, title, en, cn) => {
        const group = root.getByRole('group', { name: title, exact: true });
        await expandTranslation(group); await group.getByLabel('English', { exact: true }).fill(en); await group.getByLabel('中文', { exact: true }).fill(cn);
      };
      await page.goto(`${base}/events/new?groupId=qa-group`, { waitUntil: 'domcontentloaded', timeout: 45000 });
      await page.getByRole('button', { name: /轻松相聚|Simple social/ }).click();
      await page.getByRole('button', { name: /团契聚餐|Fellowship meal/ }).click(); await page.getByRole('button', { name: t('Start arranging', '开始安排'), exact: true }).click();
      await page.locator('[data-arrangement-tile="EVENT.DETAILS"]').click();
      await fillText(page, t('Event title', '活动名称'), 'Community meal', '社区聚餐');
      await fillText(page, t('Description', '活动说明'), 'A meal together', '一同聚餐');
      await page.getByLabel(t('Start time', '开始时间'), { exact: true }).fill('2026-10-04T18:00');
      await page.getByLabel(t('End time', '结束时间'), { exact: true }).fill('2026-10-04T20:00');
      await page.locator('[data-arrangement-tile="EVENT.DETAILS"]').click();
      assert.equal(await page.locator('footer').last().getByRole('button').count(), 1);
      await page.getByRole('button', { name: t('Back to top', '回到开头'), exact: true }).click();
      const tile = code => page.locator(`[data-arrangement-tile="${code}"]`);
      const open = async code => { const selecting = await tile(code).getAttribute('aria-expanded') !== 'true'; if (selecting) await tile(code).click(); const root = page.locator(`[data-module-editor="${code}"]`); await root.waitFor({ state: 'visible' }); if (selecting) await page.waitForFunction(code => document.activeElement === document.getElementById(`module-heading-${code}`), code); return root; };
      const work = async (root, en, cn) => { const summary = root.locator('summary').filter({ has: page.getByText(t(en, cn), { exact: true }) }); await summary.waitFor(); const card = summary.locator('..'); if (await card.getAttribute('open') === null) await summary.click(); return card; };
      const enable = async code => { const root = await open(code); await work(root, 'Settings and responsibilities', '设置与职责'); await root.getByRole('button', { name: t('Yes','是'), exact: true }).click(); return root; };
      const top = page.getByRole('group', { name: t('Event module overview', '活动模块总览'), exact: true });
      const modeButton = page.getByRole('button', { name: /显示(所有|相关)模块|Show (all|related) modules/ });
      const relatedCount = modules.filter(([moduleCode]) => relatedModules.has(moduleCode)).length;
      await top.locator('button').nth(relatedCount - 1).waitFor();
      assert.equal(await top.locator('button').count(), relatedCount);
      assert.equal((await modeButton.textContent() || '').trim(), zh ? `显示所有模块（${modules.length}）` : `Show all modules (${modules.length})`);
      assert.equal(await modeButton.count(), 1);
      await modeButton.click();
      await modeButton.waitFor();
      assert.equal(await top.locator('button').count(), 12);
      assert.equal((await modeButton.textContent() || '').trim(), zh ? `显示相关模块（${relatedCount}/${modules.length}）` : `Show related modules (${relatedCount}/${modules.length})`);
      assert.equal(await page.locator('[data-module-editor]:visible').count(), 0);
      assert.equal(await top.evaluate(el => getComputedStyle(el).gridTemplateColumns.split(' ').length), width >= 1280 ? 6 : width >= 1024 ? 4 : width >= 768 ? 3 : 2);
      assert.ok((await tile('FESTIVAL.OPERATIONS').innerText()).includes(t('Not yet available', '尚未提供')));
      for (const code of ['MONEY.FINANCE', 'FOOD.HOSPITALITY']) assert.ok((await tile(code).innerText()).includes(t('Partly available', '部分提供')));
      assert.ok((await tile('COMMS.FOLLOWUP').innerText()).includes(t('Partly available', '部分提供')));
      await page.screenshot({ path: path.join(os.tmpdir(), `alife-module-overview-${language}-${width}.png`) });
      const initialRoster = await open('SERVICE.ROSTER');
      await initialRoster.getByRole('button', { name: t('No', '否'), exact: true }).click();
      const money = await open('MONEY.FINANCE');
      await money.getByRole('button', { name: t('Yes', '是'), exact: true }).waitFor();
      await page.waitForFunction(() => !document.querySelector('[data-module-editor="MONEY.FINANCE"] button[aria-pressed]')?.disabled);
      assert.equal(await money.locator('details[data-tool-panel]:visible').count(), 1);
      await money.locator('summary').click();
      assert.equal(await money.locator('details[data-tool-panel][open]').count(), 0, 'a single configuration card can collapse');
      await open('TEAM.WORK'); await open('MONEY.FINANCE');
      assert.equal(await money.locator('details[data-tool-panel][open]').count(), 0, 'module switches preserve collapsed state');
      await enable('SERVICE.ROSTER');
      const ram = await enable('SAFETY.RAM');
      assert.equal(await ram.locator('[data-arrangement-tile]').count(), 0, 'work areas have no inner tile navigation');
      assert.equal(await ram.locator('details[data-tool-panel][open]').count(), 1, 'only settings initially opens');
      await ram.screenshot({ path: path.join(os.tmpdir(), `alife-configuration-cards-${language}-${width}.png`), animations: 'disabled', timeout: 60000 });
      const settingsSummary = ram.locator('summary').filter({ has: page.getByText(t('Settings and responsibilities', '设置与职责'), { exact: true }) });
      await settingsSummary.press('Enter');
      assert.equal(await ram.locator('details[data-tool-panel][open]').count(), 0);
      assert.equal(await settingsSummary.evaluate(el => el === document.activeElement), true);
      await settingsSummary.press('Space');
      await work(ram, 'Activities and conditions', '活动项目与条件');
      await ram.getByLabel(t('Participant count', '参与人数'), { exact: true }).fill('12');
      await work(ram, 'Risk details', '风险明细');
      assert.equal(await ram.getByLabel(t('Participant count', '参与人数'), { exact: true }).isVisible(), true);
      assert.equal(await ram.locator('details[data-tool-panel][open]').count(), 3, 'work areas expand independently');
      const conditionsSummary = ram.locator('summary').filter({ has: page.getByText(t('Activities and conditions', '活动项目与条件'), { exact: true }) });
      assert.match(await conditionsSummary.textContent(), zh ? /12 人/ : /12 people/);
      await conditionsSummary.click();
      assert.equal(await ram.getByLabel(t('Participant count', '参与人数'), { exact: true }).isVisible(), false);
      assert.equal(await ram.getByRole('button', { name: t('Add risk', '添加风险'), exact: true }).isVisible(), true);
      await work(ram, 'Activities and conditions', '活动项目与条件');
      assert.equal(await ram.getByLabel(t('Participant count', '参与人数'), { exact: true }).inputValue(), '12');
      await ram.getByRole('button', { name: t('Add risk', '添加风险'), exact: true }).click();
      await ram.locator('[data-ram-risk] > summary').first().click();
      if (zh) await ram.getByLabel('危害 (en)', { exact: true }).locator('..').locator('..').locator('summary').click();
      const privateText = 'Private RAM hazard';
      await ram.getByLabel(`${t('Hazard','危害')} (en)`, { exact: true }).fill(privateText);
      assert.ok(!(await page.evaluate(() => JSON.stringify(localStorage))).includes(privateText));
      await work(ram, 'Draft assistance and checks', '起草助手与检查');
      await conditionsSummary.click();
      await ram.getByRole('button', { name: t('Check draft and ratings', '检查草稿及评分'), exact: true }).click();
      await ram.getByRole('button', { name: t('Verify participant count', '请核实参与人数'), exact: true }).click();
      const participantControl = await ram.getByLabel(t('Participant count', '参与人数'), { exact: true }).elementHandle();
      await page.waitForFunction(control => document.activeElement === control, participantControl);
      assert.notEqual(await conditionsSummary.locator('..').getAttribute('open'), null, 'RAM check links reveal the collapsed configuration card');
      await ram.getByText(t('AI drafting / rewriting', 'AI 协助起草／改写'), { exact: true }).click();
      await ram.getByLabel(t('Non-sensitive activity brief to send', '将发送的非敏感活动概要')).fill('An indoor community meal with walking between tables.');
      await ram.getByLabel(t('This is the sending preview. I removed names, contacts, health and confidential information. The full RAM is not sent.', '以上为发送预览。我已移除姓名、联系方式、健康和保密信息；不会发送整份 RAM。'), { exact: true }).check();
      await ram.getByRole('button', { name: t('Send preview and generate suggestions', '发送预览并生成建议'), exact: true }).click();
      await ram.getByRole('button', { name: t('Adopt this suggestion into draft', '采纳此项到草稿'), exact: true }).click();
      assert.equal(creates.length, 0);
      assert.ok(!(await page.evaluate(() => JSON.stringify(localStorage))).includes('Keep the walkway clear'));
      await work(ram, 'Risk details', '风险明细');
      await ram.getByRole('button', { name: t('No', '否'), exact: true }).click();
      await ram.getByRole('button', { name: t('Yes', '是'), exact: true }).click();
      await ram.getByLabel(`${t('Hazard','危害')} (en)`, { exact: true }).first().waitFor({ state: 'visible' });
      assert.equal(await ram.getByLabel(`${t('Hazard','危害')} (en)`, { exact: true }).first().inputValue(), privateText, 'disable/re-enable retains draft and expansion');
      await page.screenshot({ path: path.join(os.tmpdir(), `alife-inline-ram-risk-${language}-${width}.png`) });
      const roster = await open('SERVICE.ROSTER'); await work(roster, 'Role shifts', '岗位轮班');
      await roster.getByLabel(t('People needed', '所需人数'), { exact: true }).fill('4');
      assert.equal(await ram.isVisible(), false);
      await open('SAFETY.RAM');
      assert.equal(await ram.getByLabel(`${t('Hazard','危害')} (en)`, { exact: true }).first().inputValue(), privateText);
      await ram.getByRole('button', { name: t('Back to modules','返回模块总览'), exact: true }).click();
      assert.equal(await page.locator('[data-module-editor]:visible').count(), 0);
      await page.waitForFunction(() => document.activeElement === document.querySelector('[data-arrangement-tile="SAFETY.RAM"]'));
      await tile('SAFETY.RAM').press('Enter');
      await page.locator('[id="module-heading-SAFETY.RAM"]').waitFor();
      await page.waitForFunction(() => document.activeElement === document.getElementById('module-heading-SAFETY.RAM'));
      const programme = await enable('PROGRAM.PRODUCTION');
      await work(programme, 'Role shifts', '岗位轮班');
      assert.equal(await programme.getByLabel(t('People needed','所需人数'), { exact: true }).inputValue(), '4');
      // Current collaboration UI prepares programme reports after creation.
      await programme.getByText(/After saving the event|保存活动后/).waitFor();
      assert.equal(await programme.getByRole('button', { name: t('Add session','添加环节'), exact: true }).count(), 0);
      const roleCard = await work(programme, 'Role shifts', '岗位轮班');
      const demand = programme.getByLabel(t('People needed','所需人数'), { exact: true });
      await demand.fill('0'); await roleCard.locator(':scope > summary').click();
      await programme.getByRole('checkbox', { name: t('Details confirmed', '填写已确认'), exact: true }).click();
      await demand.waitFor({ state: 'visible' });
      await page.waitForFunction(input => document.activeElement === input, await demand.elementHandle());
      assert.equal(await programme.getByRole('checkbox', { name: t('Details confirmed', '填写已确认'), exact: true }).isChecked(), false);
      await demand.fill('4');
      const venues = await enable('PLACE.RESOURCE'); await work(venues, 'Venue plan','场地安排');
      await venues.getByRole('button', { name: t('Add venue booking','添加场地安排'), exact: true }).click();
      await venues.getByLabel(t('Choose venue','选择场地')).selectOption('venue-1');
      await venues.getByLabel(t('Expected attendance','所需人数')).fill('51'); await venues.getByRole('alert').waitFor();
      await venues.getByLabel(t('Expected attendance','所需人数')).fill('30');
      await venues.scrollIntoViewIfNeeded(); assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
      await page.screenshot({ path: path.join(os.tmpdir(), `alife-arrangements-venue-${language}-${width}.png`) });
      await page.waitForFunction(() => !document.querySelector('[data-module-editor="PLACE.RESOURCE"] [data-module-confirmation] input').disabled);
      const fetches = venueLoads, compositions = composeLoads;
      await page.getByRole('button', { name: t('Select language, current language: English','选择语言，当前语言：中文'), exact: true }).click();
      await page.getByRole('menuitemradio', { name: zh ? 'English' : '中文', exact: true }).click();
      await page.getByRole('region', { name: zh ? 'Venue and resources' : '场地与资源', exact: true }).waitFor();
      assert.equal(venueLoads, fetches); assert.equal(composeLoads, compositions);
      assert.equal(await venues.getByLabel(zh ? 'Expected attendance' : '所需人数').inputValue(), '30');
      await page.getByRole('button', { name: zh ? 'Select language, current language: English' : '选择语言，当前语言：中文', exact: true }).click();
      await page.getByRole('menuitemradio', { name: zh ? '中文' : 'English', exact: true }).click();
      const venueConfirmation = venues.getByRole('checkbox', { name: t('Details confirmed','填写已确认'), exact: true, includeHidden: true });
      await venueConfirmation.check();
      await open('PROGRAM.PRODUCTION');
      const confirmation = programme.getByRole('checkbox', { name: t('Details confirmed','填写已确认'), exact: true });
      assert.equal(await confirmation.isChecked(), false); await confirmation.check();
      await programme.getByLabel(t('People needed','所需人数'), { exact: true }).fill('5');
      assert.equal(await confirmation.isChecked(), false); assert.equal(await venueConfirmation.isChecked(), true); await confirmation.check();
      await open('PLACE.RESOURCE'); assert.equal(await venues.getByLabel(t('Expected attendance','所需人数')).inputValue(), '30');
      await next(); await page.getByRole('heading', { name: t('Review event plan', '确认活动方案'), exact: true }).waitFor();
      await page.getByRole('heading', { name: t('Module confirmation and responsible roles', '模块确认与负责人'), exact: true }).waitFor();
      await page.getByRole('button', { name: t('Confirm and create event', '确认创建活动'), exact: true }).click();
      await page.getByRole('alert').filter({ hasText: /conflict|冲突/ }).waitFor();
      assert.equal(creates.length, 1); const payload = creates[0].body.arrangements;
      assert.equal(payload.serviceSlots[0].requiredCount, 5); assert.deepEqual(payload.sessions, []);
      assert.equal(payload.venueBookings[0].venueETag, '"venue-v1"'); assert.equal(payload.venueBookings[0].requiredCapacity, 30);
      await next(); await page.getByRole('button', { name: t('Confirm and create event', '确认创建活动'), exact: true }).click();
      await page.getByRole('alert').filter({ hasText: /Temporary/ }).waitFor();
      assert.equal(creates[1].key, creates[0].key); assert.deepEqual(creates[1].body, creates[0].body);
      assert.deepEqual(errors, []);
      console.log(`PASS ${language} ${width}: required rule, Yes/No, collapse, retained draft, validation, bilingual fields, venue capacity, summary, atomic payload, conflict recovery, idempotent retry, no language refetch, responsive layout`);
      await context.close();
    }
  } catch (error) { if (lastPage && !lastPage.isClosed()) { await lastPage.screenshot({ path: path.join(os.tmpdir(), 'alife-creation-failure.png') }); console.error(await lastPage.evaluate(() => ({ url: location.href, language: document.documentElement.lang, modules: Array.from(document.querySelectorAll('[data-module-editor]:not([hidden])')).map(el => ({ code: el.getAttribute('data-module-editor'), text: el.textContent.slice(0, 1500), cards: Array.from(el.querySelectorAll('[data-tool-panel]')).map(card => ({ open: card.open, summary: card.querySelector('summary')?.textContent })) })) }))); } throw error; } finally { await browser.close(); }
})().catch(error => { console.error(error); process.exit(1); });
