const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {chromium}=require(process.env.ALIFE_PLAYWRIGHT_MODULE||'playwright');
const base=process.env.ALIFE_BROWSER_BASE_URL||'http://127.0.0.1:5175',output=process.env.ALIFE_BROWSER_OUTPUT||require('node:os').tmpdir();
const version=JSON.parse(fs.readFileSync(path.join(__dirname,'../node_modules/.vite/deps/_metadata.json'))).browserHash;
const harness=`<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"></head><body><div id="root"></div><script type="module">
import RefreshRuntime from '/@react-refresh';RefreshRuntime.injectIntoGlobalHook(window);window.$RefreshReg$=()=>{};window.$RefreshSig$=()=>type=>type;window.__vite_plugin_react_preamble_installed__=true;
const React=(await import('/node_modules/.vite/deps/react.js?v=${version}')).default,{createRoot}=(await import('/node_modules/.vite/deps/react-dom_client.js?v=${version}')).default;
const {BrowserRouter}=await import('/node_modules/.vite/deps/react-router-dom.js?v=${version}');
const {AuthProvider}=await import('/src/stores/auth.tsx');
const {ActivityPlanEditor}=await import('/src/components/events/EventActivityPlanPanel.tsx');
const {default:Fields}=await import('/src/components/events/RamAssessmentFields.tsx');
const {default:Rating}=await import('/src/components/events/RamRatingSummary.tsx');
const {RamEditingLanguage}=await import('/src/components/events/RamFields.tsx');
const {previewRam}=await import('/src/utils/ramRatings.ts');
const {ramDefaultScales}=await import('/src/types/ramGovernance.ts');await import('/src/styles/global.css');
const text=(en,zh)=>({en,zh}),policy={...ramDefaultScales,matrix:[1,2,3,4,5].flatMap(likelihood=>[1,2,3,4,5].map(impact=>({likelihood,impact,level:likelihood*impact>=20?'Red':likelihood*impact>=6?'Yellow':'Green'}))),categories:[{code:'activity',name:text('Activity','活动'),guidance:text('','')}],questions:[],reviewRules:{reviewReminderDays:7},source:'fixture'};
function App(){const [zh,setZh]=React.useState(new URLSearchParams(location.search).get('lang')==='zh'),[plan,setPlan]=React.useState({activities:[{id:'kayak',type:'water',name:text('Kayaking','皮划艇'),conditions:text('Lifejackets required','需要救生衣')}],participantCount:20,isOuting:false,isOvernight:false,isHighRisk:false,weatherConfirmation:text('','')}),[draft,setDraft]=React.useState({schemaVersion:2,activities:plan.activities,participantCount:20,isOuting:false,isOvernight:false,isHighRisk:false,weatherConfirmation:text('',''),transport:text('',''),accommodation:text('',''),authorAttendsAndLeads:true,onsiteMemberId:null,answers:[],hazards:[{id:'risk1',activityId:'kayak',categoryCode:'activity',hazard:text('Immersion','落水'),consequence:text('Injury','受伤'),controlMeasures:text('Verify equipment','核查装备'),personResponsible:'Leader',additionalAction:text('Confirm conditions','核实条件'),likelihood:3,impact:4,residualLikelihood:1,residualImpact:4},{id:'risk2',activityId:'kayak',categoryCode:'activity',hazard:text('Cold water','冷水'),consequence:text('Injury','受伤'),controlMeasures:text('Verify equipment','核查装备'),personResponsible:'Leader',additionalAction:text('',''),likelihood:null,impact:null,residualLikelihood:null,residualImpact:null}]});return React.createElement(RamEditingLanguage.Provider,{value:zh},React.createElement('main',{style:{padding:12,maxWidth:1000,margin:'auto'}},React.createElement('button',{onClick:()=>setZh(!zh)},'Switch language'),React.createElement('section',{id:'upstream'},React.createElement(ActivityPlanEditor,{data:plan,onChange:setPlan,zh})),React.createElement('section',{id:'ram'},React.createElement(Rating,{draft:previewRam(draft,policy),zh,dirty:true}),React.createElement(Fields,{draft,update:change=>setDraft(d=>({...d,...change})),policy,editable:true,dirty:true,zh,eventId:'qa'}))));}
createRoot(document.getElementById('root')).render(React.createElement(AuthProvider,null,React.createElement(BrowserRouter,null,React.createElement(App))));
</script></body></html>`;
(async()=>{fs.mkdirSync(output,{recursive:true});const browser=await chromium.launch({headless:true});try{for(const lang of ['zh','en'])for(const width of [320,1280]){const zh=lang==='zh',t=(en,cn)=>zh?cn:en;const ctx=await browser.newContext({viewport:{width,height:950},serviceWorkers:'block'}),page=await ctx.newPage();const errors=[];page.on('pageerror',e=>{errors.push(e.message);console.error(e.message)});await ctx.route(`${base}/__ram-plan-qa**`,r=>r.fulfill({contentType:'text/html',body:harness}));await page.goto(`${base}/__ram-plan-qa?lang=${lang}`);
const upstream=page.locator('#upstream'),ram=page.locator('#ram');await upstream.locator('[data-planned-activity]').waitFor();assert.equal(await upstream.locator('[data-planned-activity]').evaluate(e=>e.open),false);await upstream.locator('[data-planned-activity] > summary').click();const primary=upstream.getByRole('textbox',{name:t('Activity name (en)','活动名称 (zh)'),exact:true});await primary.fill(t('Edited kayaking','修改后的皮划艇'));await page.getByRole('button',{name:'Switch language'}).click();await page.getByRole('button',{name:'Switch language'}).click();assert.equal(await primary.inputValue(),t('Edited kayaking','修改后的皮划艇'));
assert.equal(await ram.getByRole('button',{name:t('Add activity','添加活动项目'),exact:true}).count(),0);assert.equal(await ram.getByText(/Required questions|必答题/).count(),0);

await ram.getByText(t('Kayaking','皮划艇'),{exact:true}).first().waitFor();const activitySummary=ram.locator('[data-ram-activity] > summary').first();assert.equal(await ram.locator('[data-ram-activity]').first().evaluate(e=>e.open),false);await activitySummary.click();const risk=ram.locator('[data-ram-risk]').first();const summary=risk.locator(':scope > summary');await summary.waitFor();assert.match(await summary.innerText(),/12/);assert.match(await summary.innerText(),/4/);await summary.click();await risk.locator('select').nth(2).selectOption('5');await risk.getByText(/5 × 4 = 20/).waitFor();await summary.click();assert.match(await summary.innerText(),/20/);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await page.screenshot({path:path.join(output,`ram-plan-${lang}-${width}.png`),fullPage:true});assert.deepEqual(errors,[]);await ctx.close();console.log('PASS activity source and risk scoring',lang,width);}}finally{await browser.close()}})().catch(e=>{console.error(e);process.exitCode=1});
