import { useId, useRef, useState } from 'react'
import { useQuery, useQueryClient } from '@tanstack/react-query'
import { Link, useParams, useSearchParams } from 'react-router-dom'
import { useAuthStore } from '../stores/auth'
import { eventVenueService } from '../services/eventVenueService'
import { eventWorkService } from '../services/eventWorkService'
import { venueCalendarService, type WeeklyVenueInput, type VenueCalendarEntry, type WeeklyVenueRule } from '../services/eventVenueCalendarService'
import { normalizeApiError } from '../services/http'
import { inputStyle } from '../services/eventRegistrationWorkService'
import { BilingualRuleField } from '../components/events/EventRegistrationRulesEditor'
import AppPageShell from '../components/layout/AppPageShell'
import AppSectionCard from '../components/layout/AppSectionCard'
import AppActionButton from '../components/layout/AppActionButton'
import useConfirmation from '../hooks/useConfirmation'
import type { EventVenue, SaveEventVenueRequest } from '../types/eventVenue'

const dayString = (d: Date) => `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}-${String(d.getDate()).padStart(2, '0')}`
const timeString = (minute: number) => `${String(Math.floor(minute / 60) % 24).padStart(2, '0')}:${String(minute % 60).padStart(2, '0')}`
const minutes = (value: string) => Number(value.slice(0, 2)) * 60 + Number(value.slice(3, 5))
function VenueEditor({ group, venue, refresh }: { group: string; venue?: EventVenue; refresh: () => Promise<void> }) {
  const timeZonesId = useId()
  const { language } = useAuthStore(), zh = language === 'zh'
  const [draft, setDraft] = useState<SaveEventVenueRequest>(venue ? { name: venue.name, address: venue.address, capacity: venue.capacity, isActive: venue.isActive, timeZone: venue.timeZone || 'Pacific/Auckland', kind: venue.kind || 'venue' } : { name: { en: '', zh: '' }, address: { en: '', zh: '' }, capacity: 30, isActive: true, timeZone: Intl.DateTimeFormat().resolvedOptions().timeZone, kind: 'venue' })
  const [busy, setBusy] = useState(false), [error, setError] = useState(''), [savedTag, setSavedTag] = useState(venue?.eTag || '')
  return <form className="space-y-4" onSubmit={async e => { e.preventDefault(); if (busy) return; setBusy(true); setError(''); try { const result = venue ? await eventVenueService.updateVenue(group, venue.id, savedTag, draft) : await eventVenueService.createVenue(group, draft); setSavedTag(result.eTag); await refresh(); if (!venue) setDraft(d => ({ ...d, name: { en: '', zh: '' }, address: { en: '', zh: '' } })) } catch (e) { setError(normalizeApiError(e).message) } finally { setBusy(false) } }}>
    {error ? <p role="alert" className="text-sm text-rose-800">{error}</p> : null}<fieldset disabled={busy} className="space-y-4"><BilingualRuleField required label={zh ? '场地／房间名称' : 'Venue / room name'} value={draft.name} onChange={name => setDraft(d => ({ ...d, name }))} /><BilingualRuleField label={zh ? '地址或位置说明' : 'Address or location'} value={draft.address} onChange={address => setDraft(d => ({ ...d, address }))} /><div className="grid gap-3 sm:grid-cols-2"><label className="grid gap-2 text-sm">{zh ? '类型' : 'Type'}<select className={inputStyle} value={draft.kind} onChange={e => setDraft(d => ({ ...d, kind: e.target.value as 'venue' | 'room' }))}><option value="venue">{zh ? '场地' : 'Venue'}</option><option value="room">{zh ? '房间' : 'Room'}</option></select></label><label className="grid gap-2 text-sm">{zh ? '容量' : 'Capacity'}<input className={inputStyle} type="number" min={1} max={1000000} value={draft.capacity} onChange={e => setDraft(d => ({ ...d, capacity: Number(e.target.value) }))} required /></label></div><label className="grid gap-2 text-sm">{zh ? '场地时区' : 'Venue time zone'}<input className={inputStyle} value={draft.timeZone} list={timeZonesId} required onChange={e => setDraft(d => ({ ...d, timeZone: e.target.value }))} /><datalist id={timeZonesId}>{['Pacific/Auckland', 'Australia/Perth', 'Australia/Sydney', 'Asia/Shanghai', 'Europe/London', 'America/Los_Angeles'].map(zone => <option key={zone} value={zone} />)}</datalist></label><label className="flex min-h-11 items-center gap-3 text-sm"><input type="checkbox" checked={draft.isActive} onChange={e => setDraft(d => ({ ...d, isActive: e.target.checked }))} />{zh ? '启用' : 'Active'}</label><AppActionButton type="submit" disabled={busy} variant="primary">{venue ? zh ? '保存场地资料' : 'Save venue' : zh ? '新增场地或房间' : 'Add venue or room'}</AppActionButton></fieldset>
  </form>
}
export function VenueCalendarWorkspace({ groupId, embedded = false }: { groupId: string; embedded?: boolean }) {
  const { me, language } = useAuthStore(), zh = language === 'zh', cache = useQueryClient(), [params, setParams] = useSearchParams()
  const catalogue = useQuery({ queryKey: ['venue-catalogue', me?.id, groupId], queryFn: () => eventVenueService.listReservableCatalogue(groupId), gcTime: 0, retry: false })
  const [venueId, setVenueId] = useState(params.get('venue') || ''), [from, setFrom] = useState(dayString(new Date())), [until, setUntil] = useState(dayString(new Date(Date.now() + 30 * 86400000)))
  const venue = catalogue.data?.venues.find(v => v.id === venueId)
  const calendar = useQuery({ queryKey: ['venue-calendar', me?.id, groupId, venueId, from, until], queryFn: () => venueCalendarService.get(groupId, venueId, from, until), enabled: Boolean(venueId && from && until), gcTime: 0, retry: false })
  const eventPage = Math.max(1, Number(params.get('eventPage')) || 1), eventSearch = params.get('eventSearch') || ''
  const events = useQuery({ queryKey: ['venue-event-choices', me?.id, groupId, eventPage, eventSearch], queryFn: () => eventWorkService.list(eventPage, eventSearch), gcTime: 0 })
  const [input, setInput] = useState<WeeklyVenueInput>({ eventId: params.get('event') || '', firstDate: from, lastDate: null, startMinute: 540, endMinute: 720, requiredCapacity: 30, replacesRuleId: null, reason: '' })
  const [replacementTag, setReplacementTag] = useState(''), [busy, setBusy] = useState(false), [error, setError] = useState(''), [notice, setNotice] = useState(''), [reason, setReason] = useState(''), [entry, setEntry] = useState<VenueCalendarEntry | null>(null)
  const [search, setSearch] = useState(''), [entryPage, setEntryPage] = useState(1), [cataloguePage, setCataloguePage] = useState(1)
  const attempt = useRef<{ signature: string; id: string } | null>(null), { requestConfirmation, confirmationModal } = useConfirmation()
  const refresh = async () => { await cache.invalidateQueries({ queryKey: ['venue-calendar', me?.id, groupId] }); await cache.invalidateQueries({ queryKey: ['venue-catalogue', me?.id, groupId] }); await cache.invalidateQueries({ queryKey: ['event-work', me?.id] }) }
  const run = async (signature: string, fn: (key: string) => Promise<unknown>) => {
    if (busy) return
    if (!await requestConfirmation({ title: zh ? '确认预约操作' : 'Confirm reservation change', description: zh ? '请核对当地日期、时间和原因。服务端会再次核实冲突，保留操作记录。' : 'Check the local date, time and reason. The server checks conflicts again and keeps a history.', confirmLabel: zh ? '确认' : 'Confirm' })) return
    if (attempt.current?.signature !== signature) attempt.current = { signature, id: crypto.randomUUID() }
    setBusy(true); setError(''); setNotice('')
    try { await fn(attempt.current.id); attempt.current = null; await refresh(); setEntry(null); setReason(''); setInput(i => ({ ...i, replacesRuleId: null, reason: '' })); setNotice(zh ? '预约日历已更新。' : 'Reservation calendar updated.') } catch (e) { setError(normalizeApiError(e).message); await refresh() } finally { setBusy(false) }
  }
  const choose = (v: EventVenue) => { setVenueId(v.id); setEntry(null); setEntryPage(1); setInput(i => ({ ...i, requiredCapacity: Math.min(i.requiredCapacity, v.capacity), replacesRuleId: null })); setParams(p => { const next = new URLSearchParams(p); next.set('venue', v.id); return next }) }
  const replace = (rule: WeeklyVenueRule) => { setInput({ eventId: rule.eventId || '', firstDate: from > rule.firstDate ? from : dayString(new Date(new Date(rule.firstDate + 'T12:00').getTime() + 7 * 86400000)), lastDate: rule.lastDate, startMinute: rule.startMinute, endMinute: rule.endMinute, requiredCapacity: rule.requiredCapacity, replacesRuleId: rule.id, reason: '' }); setReplacementTag(rule.eTag); document.getElementById('weekly-reservation-heading')?.focus() }
  const filtered = catalogue.data?.venues.filter(v => `${v.name.en} ${v.name.zh}`.toLocaleLowerCase().includes(search.toLocaleLowerCase())).sort((a, b) => (a.name[language] || a.name.en).localeCompare(b.name[language] || b.name.en)) || []
  const entries = calendar.data?.entries || [], eventChoices = events.data?.items.filter(e => e.groupId === groupId && e.canManage) || []
  const title = zh ? '场地与房间' : 'Venues and rooms'
  const subtitle = zh ? '管理目录、每周占用和单次例外。场地时间按其当地时区显示。' : 'Manage the directory, weekly reservations and date exceptions. Times use each venue’s local time zone.'
  const workspace = <>{confirmationModal}
    {error ? <p role="alert" className="rounded-xl bg-rose-50 p-4 text-sm text-rose-800">{error}</p> : null}{notice ? <p role="status" className="rounded-xl bg-[#e3f0eb] p-4 text-sm">{notice}</p> : null}
    {catalogue.error ? <AppSectionCard><p role="alert">{normalizeApiError(catalogue.error).message}</p><AppActionButton onClick={() => void catalogue.refetch()}>{zh ? '重试' : 'Retry'}</AppActionButton></AppSectionCard> : !catalogue.data ? <p role="status">{zh ? '正在读取场地…' : 'Loading venues…'}</p> : <>
      <AppSectionCard title={zh ? '场地目录' : 'Venue directory'}><label className="grid gap-2 text-sm">{zh ? '搜索场地（名称排序）' : 'Search venues (name order)'}<input className={inputStyle} value={search} onChange={e => { setSearch(e.target.value); setCataloguePage(1) }} /></label><div className="mt-4 grid gap-3 sm:grid-cols-2">{filtered.slice((cataloguePage - 1) * 20, cataloguePage * 20).map(v => <button key={v.id} type="button" aria-pressed={v.id === venueId} className={`min-h-20 rounded-xl border p-4 text-left ${v.id === venueId ? 'border-[#176b5a] bg-[#e3f0eb]' : 'bg-white'}`} onClick={() => choose(v)}><strong>{v.name[language] || v.name.en || v.name.zh}{v.managingGroupId !== groupId ? zh ? ' · 教会共享' : ' · Church shared' : ''}</strong><span className="mt-2 block text-xs">{v.kind === 'room' ? zh ? '房间' : 'Room' : zh ? '场地' : 'Venue'} · {zh ? '容量' : 'Capacity'} {v.capacity} · {v.isActive ? zh ? '启用' : 'Active' : zh ? '停用' : 'Inactive'}</span></button>)}</div>{!filtered.length ? <p className="mt-3 text-sm">{zh ? '没有符合条件的场地。' : 'No matching venues.'}</p> : null}<div className="mt-3 flex gap-3"><AppActionButton disabled={cataloguePage <= 1} onClick={() => setCataloguePage(p => p - 1)}>{zh ? '上一页' : 'Previous'}</AppActionButton><AppActionButton disabled={filtered.length <= cataloguePage * 20} onClick={() => setCataloguePage(p => p + 1)}>{zh ? '下一页' : 'Next'}</AppActionButton></div></AppSectionCard>
      {catalogue.data.canManage ? <details className="rounded-2xl border bg-white p-5"><summary className="min-h-11 cursor-pointer font-semibold">{zh ? '新增场地或房间' : 'Add a venue or room'}</summary><VenueEditor group={groupId} refresh={refresh} /></details> : null}
      {venue ? <>{catalogue.data.canManage && venue.managingGroupId === groupId ? <details className="rounded-2xl border bg-white p-5"><summary className="min-h-11 cursor-pointer font-semibold">{zh ? '编辑场地资料' : 'Edit venue details'} · {venue.name[language] || venue.name.en}</summary><VenueEditor key={venue.id} group={groupId} venue={venue} refresh={refresh} /></details> : null}
        <AppSectionCard title={`${venue.name[language] || venue.name.en} · ${zh ? '占用日历' : 'Reservation calendar'}`}><p className="mb-3 text-sm">{venue.timeZone || 'Pacific/Auckland'}</p><div className="grid gap-3 sm:grid-cols-2"><label className="grid gap-2 text-sm">{zh ? '从' : 'From'}<input className={inputStyle} type="date" value={from} onChange={e => { setFrom(e.target.value); setEntryPage(1) }} /></label><label className="grid gap-2 text-sm">{zh ? '至（最多一年）' : 'Until (up to one year)'}<input className={inputStyle} type="date" value={until} onChange={e => { setUntil(e.target.value); setEntryPage(1) }} /></label></div>{calendar.error ? <p role="alert" className="mt-3 text-sm">{normalizeApiError(calendar.error).message}</p> : calendar.isFetching ? <p role="status" className="mt-3">{zh ? '正在读取占用…' : 'Loading reservations…'}</p> : <div className="mt-4 space-y-3">{entries.slice((entryPage - 1) * 20, entryPage * 20).map(e => <article key={`${e.bookingId}:${e.startUtc}`} className={`rounded-xl border p-4 ${e.released ? 'border-dashed text-[#66766f]' : 'bg-[#f5f2eb]'}`}><h3 className="font-semibold">{e.title[language] || e.title.en}</h3><p className="mt-2 text-sm">{new Date(e.startUtc).toLocaleString(language, { timeZone: calendar.data!.timeZone })} – {new Date(e.endUtc).toLocaleString(language, { timeZone: calendar.data!.timeZone })}</p><p className="mt-1 text-xs">{e.weekly ? zh ? '每周重复' : 'Weekly' : zh ? '单次预约' : 'Single reservation'}{e.released ? zh ? ' · 此次已释放' : ' · Released for this date' : ''}</p>{e.invalidLocalTime ? <p role="alert" className="mt-2 text-sm text-amber-900">{zh ? '夏令时使此时段不明确。当前保守占用，请管理员明确调整。' : 'A daylight-saving transition makes this interval ambiguous. It remains conservatively occupied until an administrator corrects it.'}</p> : null}{e.canManage && e.weekly ? <AppActionButton className="mt-3" disabled={busy} onClick={() => { setEntry(e); setReason('') }}>{e.released ? zh ? '恢复此日占用' : 'Restore this date' : zh ? '释放此日占用' : 'Release this date'}</AppActionButton> : null}</article>)}{!entries.length ? <p className="text-sm">{zh ? '所选日期没有占用。预约提交时仍会再次检查冲突。' : 'No reservations in this range. Submitting a reservation checks conflicts again.'}</p> : null}</div>}<div className="mt-3 flex gap-3"><AppActionButton disabled={entryPage <= 1} onClick={() => setEntryPage(p => p - 1)}>{zh ? '上一页' : 'Previous'}</AppActionButton><AppActionButton disabled={entries.length <= entryPage * 20} onClick={() => setEntryPage(p => p + 1)}>{zh ? '下一页' : 'Next'}</AppActionButton></div>
          {entry ? <form className="mt-4 space-y-3 rounded-xl border p-4" onSubmit={e => { e.preventDefault(); void run(JSON.stringify([entry, reason]), key => venueCalendarService.exception(groupId, venueId, entry, !entry.released, reason, key)) }}><p className="text-sm">{entry.localDate} · {entry.released ? zh ? '恢复这一次占用' : 'Restore this occurrence' : zh ? '仅释放这一次占用' : 'Release this occurrence only'}</p><label className="grid gap-2 text-sm">{zh ? '原因' : 'Reason'}<textarea className={inputStyle} value={reason} maxLength={2000} required onChange={e => setReason(e.target.value)} /></label><div className="flex gap-3"><AppActionButton type="submit" disabled={busy || !reason.trim()}>{zh ? '确认' : 'Confirm'}</AppActionButton><AppActionButton onClick={() => setEntry(null)}>{zh ? '取消' : 'Cancel'}</AppActionButton></div></form> : null}
        </AppSectionCard>
        <AppSectionCard title={zh ? '每周占用规则' : 'Weekly reservation rules'}>{calendar.data?.rules.map(rule => <div key={rule.id} className="border-b py-3 text-sm"><p>{rule.firstDate} → {rule.lastDate || (zh ? '无终止日期' : 'No end date')} · {timeString(rule.startMinute)}–{timeString(rule.endMinute)}{rule.endMinute >= 1440 ? zh ? '（次日）' : ' (next day)' : ''}</p>{rule.canManage ? <AppActionButton className="mt-2" onClick={() => replace(rule)}>{zh ? '从指定日期起调整' : 'Change from a date'}</AppActionButton> : null}</div>)}
          <h3 id="weekly-reservation-heading" tabIndex={-1} className="my-4 scroll-mt-24 font-semibold">{input.replacesRuleId ? zh ? '调整后续每周占用' : 'Change future weekly reservations' : zh ? '新增每周占用' : 'Add a weekly reservation'}</h3><form onSubmit={e => { e.preventDefault(); void run(JSON.stringify([input, venue.eTag, replacementTag]), key => venueCalendarService.weekly(groupId, venueId, input, input.replacesRuleId ? replacementTag : venue.eTag, key)) }}><fieldset disabled={busy || !venue.isActive} className="space-y-4">
            {!input.replacesRuleId ? <><label className="grid gap-2 text-sm">{zh ? '搜索我负责的活动' : 'Search events I own'}<input className={inputStyle} value={eventSearch} onChange={e => setParams(p => { const next = new URLSearchParams(p); next.set('eventSearch', e.target.value); next.delete('eventPage'); return next })} /></label><label className="grid gap-2 text-sm">{zh ? '占用活动' : 'Reserving event'}<select className={inputStyle} value={input.eventId} required onChange={e => setInput(i => ({ ...i, eventId: e.target.value }))}><option value="">{zh ? '选择本组活动' : 'Select an event in this group'}</option>{eventChoices.map(e => <option key={e.eventId} value={e.eventId}>{e.title[language] || e.title.en}</option>)}</select></label><div className="flex gap-3"><AppActionButton disabled={eventPage <= 1} onClick={() => setParams(p => { const n = new URLSearchParams(p); n.set('eventPage', String(eventPage - 1)); return n })}>{zh ? '前一页活动' : 'Previous events'}</AppActionButton><AppActionButton disabled={!events.data?.hasMore} onClick={() => setParams(p => { const n = new URLSearchParams(p); n.set('eventPage', String(eventPage + 1)); return n })}>{zh ? '后一页活动' : 'Next events'}</AppActionButton></div></> : <label className="grid gap-2 text-sm">{zh ? '调整原因' : 'Reason for change'}<textarea className={inputStyle} maxLength={2000} required value={input.reason} onChange={e => setInput(i => ({ ...i, reason: e.target.value }))} /></label>}
            <div className="grid gap-3 sm:grid-cols-2"><label className="grid gap-2 text-sm">{zh ? '首次日期（决定星期几）' : 'First date (sets weekday)'}<input className={inputStyle} type="date" required value={input.firstDate} onChange={e => setInput(i => ({ ...i, firstDate: e.target.value }))} /></label><label className="grid gap-2 text-sm">{zh ? '结束日期（留空为无限期）' : 'End date (blank for indefinite)'}<input className={inputStyle} type="date" value={input.lastDate || ''} onChange={e => setInput(i => ({ ...i, lastDate: e.target.value || null }))} /></label><label className="grid gap-2 text-sm">{zh ? '当地开始时间' : 'Local start time'}<input className={inputStyle} type="time" required value={timeString(input.startMinute)} onChange={e => setInput(i => ({ ...i, startMinute: minutes(e.target.value) }))} /></label><label className="grid gap-2 text-sm">{zh ? '当地结束时间' : 'Local end time'}<input className={inputStyle} type="time" required value={timeString(input.endMinute)} onChange={e => setInput(i => ({ ...i, endMinute: minutes(e.target.value) + (i.endMinute >= 1440 ? 1440 : 0) }))} /></label></div><label className="flex min-h-11 items-center gap-3 text-sm"><input type="checkbox" checked={input.endMinute >= 1440} onChange={e => setInput(i => ({ ...i, endMinute: i.endMinute % 1440 + (e.target.checked ? 1440 : 0) }))} />{zh ? '结束于次日' : 'Ends the next day'}</label><label className="grid gap-2 text-sm">{zh ? '所需容量' : 'Required capacity'}<input className={inputStyle} type="number" min={1} max={venue.capacity} required value={input.requiredCapacity} onChange={e => setInput(i => ({ ...i, requiredCapacity: Number(e.target.value) }))} /></label><p className="text-xs text-[#66766f]">{zh ? '无限期预约不会延长活动审批的有效范围；每个执行场次仍须有适用审批。' : 'An indefinite reservation does not extend approval coverage. Each event occurrence still needs applicable approval.'}</p><div className="flex flex-wrap gap-3"><AppActionButton type="submit" variant="primary" disabled={!input.eventId || busy}>{zh ? '保存每周占用' : 'Save weekly reservation'}</AppActionButton>{input.replacesRuleId ? <AppActionButton onClick={() => setInput(i => ({ ...i, replacesRuleId: null, reason: '' }))}>{zh ? '取消调整' : 'Cancel change'}</AppActionButton> : null}</div>
            {input.eventId ? <Link className="inline-flex min-h-11 items-center text-[#176b5a]" to={`/events/${input.eventId}/workspace?tab=resource`}>{zh ? '单次预约：进入活动场地工作页' : 'Single reservations: open the event venue workspace'}</Link> : null}
          </fieldset></form>
        </AppSectionCard>
        {calendar.data?.history?.length ? <AppSectionCard title={zh ? '预约操作记录' : 'Reservation history'}><p className="mb-3 text-xs text-[#66766f]">{zh ? '显示相关规则的建立记录，以及所选日期范围内的释放和恢复。' : 'Shows creation of the relevant rules and releases or restorations within the selected dates.'}</p><details><summary className="cursor-pointer py-3 text-sm">{zh ? '查看记录' : 'View records'} ({calendar.data.history.length})</summary><ol className="space-y-3">{calendar.data.history.map((h, i) => <li key={`${h.ruleId}:${h.createdUtc}:${i}`} className="border-b py-2 text-sm"><p>{h.localDate} · {({ create: zh ? '建立预约' : 'Created', 'change-future': zh ? '调整后续预约' : 'Changed future reservations', release: zh ? '释放' : 'Released', restore: zh ? '恢复' : 'Restored' } as Record<string, string>)[h.action] || h.action}</p><p className="whitespace-pre-wrap break-words">{h.reason}</p><time className="text-xs text-[#66766f]">{new Date(h.createdUtc).toLocaleString(language === 'zh' ? 'zh-CN' : 'en', { timeZone: venue.timeZone })}</time></li>)}</ol></details></AppSectionCard> : null}
      </> : <p className="text-sm">{zh ? '选择场地以查看日历和占用规则。' : 'Select a venue to view its calendar and reservation rules.'}</p>}
    </>}
  </>

  return embedded ? (
    <section className="space-y-4">
      <header className="border-b border-[#2f4b42]/10 pb-4">
        <h2 className="text-base font-black leading-tight text-[#18332d] sm:text-lg">{title}</h2>
        <p className="mt-1 max-w-3xl text-sm leading-6 text-[#66766f]">{subtitle}</p>
      </header>
      {workspace}
    </section>
  ) : (
    <AppPageShell title={title} subtitle={subtitle} backLink={{ to: `/groups/${groupId}/manage`, label: zh ? '返回管理' : 'Back to management' }}>
      {workspace}
    </AppPageShell>
  )
}
export default function EventVenueCalendarView() { const { groupId = '' } = useParams(), { me } = useAuthStore(); return <VenueCalendarWorkspace key={`${me?.id}:${groupId}`} groupId={groupId} /> }
