import { useEffect, useRef, useState } from 'react'
import { useQuery, useQueryClient } from '@tanstack/react-query'
import { Link, useParams, useSearchParams } from 'react-router-dom'
import { useAuthStore } from '../stores/auth'
import { groupService } from '../services/groupService'
import { normalizeApiError } from '../services/http'
import { registrationWorkService as service, registrationStatus, inputStyle, localDateTime, type ApplicationInput, type PersonInput, type RegistrationApplication, type RegistrationPerson, type RegistrationWork } from '../services/eventRegistrationWorkService'
import { invalidateCurrentTasks } from '../hooks/useCurrentTasks'
import useConfirmation from '../hooks/useConfirmation'
import AppPageShell from '../components/layout/AppPageShell'
import AppSectionCard from '../components/layout/AppSectionCard'
import AppActionButton from '../components/layout/AppActionButton'
import EventRegistrationRulesEditor from '../components/events/EventRegistrationRulesEditor'
import { currencyScale } from '../services/eventRegistrationWorkService'
import { setUnsavedChangesGuard } from '../utils/unsavedChangesGuard'

const emptyPerson = (): PersonInput => ({ memberId: null, displayName: '', isChild: false, guardianName: '', guardianMemberId: null })
type MemberOption = { id: string; name: string }
type Action = (app: RegistrationApplication, operation: string, body?: object, confirm?: boolean) => Promise<void>
const fee = (minor: number, currency: string, language: string) => { const format = new Intl.NumberFormat(language, { style: 'currency', currency }); return format.format(minor / 10 ** (format.resolvedOptions().maximumFractionDigits ?? 2)) }

function Participant({ work, app, person: p, act, busy, refresh }: { work: RegistrationWork; app: RegistrationApplication; person: RegistrationPerson; act: Action; busy: boolean; refresh: () => Promise<void> }) {
  const { me, language } = useAuthStore(), zh = language === 'zh', rules = work.policy!.rules
  const self = p.isChild ? p.guardianMemberId === me?.id : p.memberId === me?.id
  const manage = work.canManage, edit = manage || app.organiserMemberId === me?.id && !p.proxyAccessRevoked || self
  const [answers, setAnswers] = useState<Record<string, string>>(() => { try { const parsed: unknown = JSON.parse(p.answersJson); return parsed && typeof parsed === 'object' && !Array.isArray(parsed) ? parsed as Record<string, string> : {} } catch { return {} } })
  const [evidence, setEvidence] = useState(''), [consentTime, setConsentTime] = useState(localDateTime(new Date().toISOString())), [amount, setAmount] = useState(''), [error, setError] = useState(''), [uploading, setUploading] = useState(false)
  const files = useQuery({ queryKey: ['registration-files', me?.id, work.eventId, p.id], queryFn: () => service.files(work.eventId, p.id), enabled: edit, retry: false, gcTime: 0 })
  const ended = ['cancelled', 'expired'].includes(p.seatStatus), writable = edit && !ended && p.seatStatus !== 'confirmed'
  const dirty = writable && JSON.stringify(answers) !== p.answersJson
  useEffect(() => {
    const scope = `registration-answers:${me?.id}:${p.id}`
    setUnsavedChangesGuard(dirty, zh ? '报名材料有未保存修改。' : 'Registration answers have unsaved changes.', 'confirm', scope)
    return () => setUnsavedChangesGuard(false, '', 'confirm', scope)
  }, [dirty, zh, me?.id, p.id])
  const action = (operation: string, body: object = {}, confirm = true) => act(app, operation, { participantId: p.id, ...body }, confirm)
  const upload = async (requirement: string, file: File) => {
    const rule = rules.materials.find(m => m.id === requirement)!
    if (file.size > rule.maxBytes) { setError(zh ? '文件超过规定大小。' : 'The file exceeds the size limit.'); return }
    setUploading(true); setError('')
    try { await service.upload(work.eventId, p.id, requirement, file, app.eTag); await files.refetch(); await refresh() }
    catch (e) { setError(normalizeApiError(e).message) } finally { setUploading(false) }
  }
  return <div className="space-y-4 rounded-xl border border-[#176b5a]/20 p-4">
    <h3 className="text-lg font-semibold">{p.displayName}{p.isChild ? ` · ${zh ? '儿童' : 'Child'}` : ''}</h3>
    <dl className="grid gap-3 text-sm sm:grid-cols-3"><div><dt className="text-[#66766f]">{zh ? '手续' : 'Procedures'}</dt><dd>{registrationStatus(p.procedureStatus, zh)}</dd></div><div><dt className="text-[#66766f]">{zh ? '名额' : 'Place'}</dt><dd>{registrationStatus(p.seatStatus, zh)}</dd></div><div><dt className="text-[#66766f]">{zh ? '已核实净付款' : 'Verified net payment'}</dt><dd>{fee(p.paidMinor - p.refundedMinor, rules.currency, language)} / {fee(rules.feeMinor, rules.currency, language)}</dd></div></dl>
    {p.isLegacy ? <p className="text-xs text-[#66766f]">{zh ? '此记录来自旧报名。未知家庭成员和历史同意未补造。' : 'This record came from legacy registration. Unknown household members and historical consent have not been inferred.'}</p> : null}
    {error ? <p role="alert" className="text-sm text-rose-800">{error}</p> : null}
    {edit ? <><p className="text-sm">{p.consentedUtc ? `${zh ? '同意已记录' : 'Consent recorded'} · ${new Date(p.consentedUtc).toLocaleString(language)}` : zh ? '尚缺本人或监护人同意。代填资料不能代替本人同意。' : 'Personal or guardian consent is still needed. Proxy entry does not provide consent.'}</p>
      {self && !p.consentedUtc && writable ? <AppActionButton disabled={busy} onClick={() => void action('consent')}>{p.isChild ? zh ? '我作为监护人同意规则' : 'I agree as the guardian' : zh ? '我本人同意参加规则与隐私说明' : 'I personally agree to the rules and privacy notice'}</AppActionButton> : null}
      {rules.materials.filter(m => m.kind === 'text').map(m => <label key={m.id} className="grid gap-2 text-sm">{m.label[language] || m.label.en || m.label.zh}{m.required ? ' *' : ''}<textarea disabled={!writable || busy} className={`${inputStyle} min-h-24`} maxLength={10000} value={typeof answers[m.id] === 'string' ? answers[m.id] : ''} onChange={e => setAnswers(a => ({ ...a, [m.id]: e.target.value }))} /></label>)}
      {rules.materials.some(m => m.kind === 'text') && writable ? <AppActionButton disabled={busy} onClick={() => void action('answers', { answersJson: JSON.stringify(Object.fromEntries(rules.materials.filter(m => m.kind === 'text').map(m => [m.id, answers[m.id] || '']))) }, false)}>{zh ? '保存文字材料' : 'Save answers'}</AppActionButton> : null}
      {rules.materials.filter(m => m.kind !== 'text').map(m => <div key={m.id} className="space-y-2"><label className="grid gap-2 text-sm">{m.label[language] || m.label.en || m.label.zh}{m.required ? ' *' : ''}<span className="text-xs text-[#66766f]">{zh ? '最多' : 'Maximum'} {m.maxCount} · {m.maxBytes / 1048576} MB · {m.kind === 'image' ? 'JPG / PNG' : 'JPG / PNG / PDF / TXT'}</span>{writable ? <input type="file" className={inputStyle} disabled={busy || uploading || (files.data?.filter(f => f.requirementId === m.id).length || 0) >= m.maxCount} accept={m.kind === 'image' ? '.jpg,.jpeg,.png' : '.jpg,.jpeg,.png,.pdf,.txt'} onChange={e => { const file = e.target.files?.[0]; e.target.value = ''; if (file) void upload(m.id, file) }} /> : null}</label>{files.data?.filter(f => f.requirementId === m.id).map(f => <span key={f.id} className="flex flex-wrap gap-2"><AppActionButton onClick={async () => { setError(''); try { await service.open(f) } catch (e) { setError(normalizeApiError(e).message) } }}>{f.name}</AppActionButton>{writable ? <AppActionButton disabled={busy || uploading} onClick={async () => { await action('remove-material', { fileAssetId: f.id }); await files.refetch() }}>{zh ? '移除并重新提交' : 'Remove to replace'}</AppActionButton> : null}</span>)}</div>)}
      {files.error ? <p role="alert" className="text-sm">{normalizeApiError(files.error).message}</p> : null}
    </> : null}
    {(manage || work.canFinance) ? <label className="grid gap-2 text-sm">{zh ? '核实方式、依据或收退款凭证' : 'Verification method, basis or receipt/refund evidence'}<textarea className={inputStyle} maxLength={2000} value={evidence} onChange={e => setEvidence(e.target.value)} /></label> : null}
    {manage && !ended ? <fieldset disabled={busy || !evidence.trim()} className="space-y-3"><label className="grid gap-2 text-sm">{zh ? '线下同意的实际时间' : 'Actual offline consent time'}<input className={inputStyle} type="datetime-local" value={consentTime} onChange={e => setConsentTime(e.target.value)} /></label><div className="flex flex-wrap gap-2"><AppActionButton disabled={!consentTime} onClick={() => void action('verify-consent', { evidence, occurredUtc: new Date(consentTime).toISOString() })}>{zh ? '记录已核实的线下同意' : 'Record verified offline consent'}</AppActionButton>{rules.manualReview ? <><AppActionButton onClick={() => void action('verify-eligibility', { evidence })}>{zh ? '确认资格核实' : 'Verify eligibility'}</AppActionButton><AppActionButton onClick={() => void action('verify-materials', { evidence })}>{zh ? '确认材料核实' : 'Verify materials'}</AppActionButton></> : null}</div></fieldset> : null}
    {work.canFinance && rules.feeMinor > 0 ? <fieldset disabled={busy} className="space-y-3"><label className="grid gap-2 text-sm">{zh ? '本次登记金额' : 'Amount to record'}<input className={inputStyle} type="number" min={1 / currencyScale(rules.currency)} step={1 / currencyScale(rules.currency)} value={amount} onChange={e => setAmount(e.target.value)} /></label><div className="flex flex-wrap gap-2"><AppActionButton disabled={!evidence.trim() || Number(amount) <= 0 || ended} onClick={() => void action('payment', { evidence, amountMinor: Math.round(Number(amount) * currencyScale(rules.currency)) })}>{zh ? '核实收到报名费' : 'Verify fee received'}</AppActionButton><AppActionButton disabled={!evidence.trim() || Number(amount) <= 0 || p.paidMinor <= p.refundedMinor || !ended} onClick={() => void action('refund', { evidence, amountMinor: Math.round(Number(amount) * currencyScale(rules.currency)) })}>{zh ? '登记退款' : 'Record refund'}</AppActionButton></div></fieldset> : null}
    {writable ? <AppActionButton disabled={busy || uploading || dirty} variant="primary" onClick={() => void action('complete')}>{zh ? '完成此人的报名手续' : 'Complete this person’s procedures'}</AppActionButton> : null}
    {self && app.organiserMemberId !== me?.id && !p.proxyAccessRevoked ? <AppActionButton disabled={busy} onClick={() => void action('revoke-proxy')}>{zh ? '撤回此人的代办权限' : 'Withdraw proxy authority'}</AppActionButton> : null}
    {edit && !ended && (app.allowSplit || app.participants.length === 1) ? <AppActionButton disabled={busy} onClick={() => void action('cancel')}>{zh ? '取消此人报名' : 'Cancel this participant'}</AppActionButton> : null}
  </div>
}

function NewApplication({ work, members, create, busy }: { work: RegistrationWork; members: MemberOption[]; create: (input: ApplicationInput) => Promise<void>; busy: boolean }) {
  const { me, language } = useAuthStore(), zh = language === 'zh'
  const [input, setInput] = useState<ApplicationInput>({ organiserMemberId: me!.id, participants: [{ ...emptyPerson(), memberId: me!.id, displayName: me!.displayName || '' }], allowSplit: false, isInvitation: work.canManage && !work.publiclyOpen, invitationMode: 'byDeadline', reservationExpiresUtc: work.policy!.rules.deadlineUtc, channel: work.policy!.rules.channel === 'manual' ? 'manual' : 'app', manualOrganiserName: '', proxyAuthorityEvidence: '' })
  const change = (i: number, patch: Partial<PersonInput>) => setInput(a => ({ ...a, participants: a.participants.map((p, index) => index === i ? { ...p, ...patch } : p) }))
  return <AppSectionCard title={zh ? '新增办理记录' : 'Start an application'}><form onSubmit={e => { e.preventDefault(); void create(input) }}><fieldset disabled={busy} className="space-y-4">
    {work.canManage ? <><label className="grid gap-2 text-sm">{zh ? '办理账号（与实际参加者分开）' : 'Organising account (separate from participants)'}<select className={inputStyle} value={input.organiserMemberId} onChange={e => setInput(a => ({ ...a, organiserMemberId: e.target.value, allowSplit: false }))}>{members.map(m => <option key={m.id} value={m.id}>{m.name}</option>)}</select></label><label className="flex min-h-11 items-center gap-3 text-sm"><input type="checkbox" checked={input.isInvitation} onChange={e => setInput(a => ({ ...a, isInvitation: e.target.checked }))} />{zh ? '先整理定向邀请名单' : 'Prepare a named invitation'}</label><label className="grid gap-2 text-sm">{zh ? '办理方式' : 'Entry channel'}<select className={inputStyle} value={input.channel} onChange={e => setInput(a => ({ ...a, channel: e.target.value }))}><option value="app">{zh ? 'App 办理' : 'App'}</option><option value="manual">{zh ? '人工登记' : 'Manual entry'}</option></select></label></> : null}
    {input.isInvitation ? <><label className="grid gap-2 text-sm">{zh ? '邀请要求' : 'Invitation requirement'}<select className={inputStyle} value={input.invitationMode} onChange={e => setInput(a => ({ ...a, invitationMode: e.target.value }))}><option value="now">{zh ? '现在办理确认' : 'Complete now'}</option><option value="byDeadline">{zh ? '截止日前补完手续' : 'Complete by deadline'}</option></select></label><label className="grid gap-2 text-sm">{zh ? '邀请截止与预留到期时间' : 'Invitation and reservation deadline'}<input className={inputStyle} type="datetime-local" required value={localDateTime(input.reservationExpiresUtc!)} onChange={e => e.target.value && setInput(a => ({ ...a, reservationExpiresUtc: new Date(e.target.value).toISOString() }))} /></label><p className="text-sm">{zh ? '此操作只保存名单。活动审批通过后，才能发送邀请并预留名额。' : 'This saves an internal list. Invitations and reservations require approved event plans.'}</p></> : null}
    {input.participants.map((p, i) => <fieldset key={i} className="space-y-3 rounded-xl border p-4"><legend className="px-2 text-sm">{zh ? '实际参加者' : 'Participant'} {i + 1}</legend><label className="grid gap-2 text-sm">{zh ? '参加者账号' : 'Participant account'}<select className={inputStyle} value={p.memberId || ''} onChange={e => change(i, { memberId: e.target.value || null, displayName: members.find(m => m.id === e.target.value)?.name || p.displayName })}><option value="">{zh ? '无账号访客' : 'Guest without an account'}</option>{members.map(m => <option key={m.id} value={m.id}>{m.name}</option>)}</select></label><label className="grid gap-2 text-sm">{zh ? '姓名' : 'Name'}<input className={inputStyle} maxLength={200} required value={p.displayName} onChange={e => change(i, { displayName: e.target.value })} /></label><label className="flex min-h-11 items-center gap-3 text-sm"><input type="checkbox" checked={p.isChild} onChange={e => change(i, { isChild: e.target.checked })} />{zh ? '这是儿童' : 'This participant is a child'}</label>{p.isChild ? <><label className="grid gap-2 text-sm">{zh ? '监护人姓名（明确填写）' : 'Guardian name (explicitly specified)'}<input className={inputStyle} required maxLength={200} value={p.guardianName} onChange={e => change(i, { guardianName: e.target.value })} /></label><label className="grid gap-2 text-sm">{zh ? '监护人账号' : 'Guardian account'}<select className={inputStyle} value={p.guardianMemberId || ''} onChange={e => change(i, { guardianMemberId: e.target.value || null })}><option value="">{zh ? '无账号，由负责人核实线下同意' : 'No account; manager verifies offline consent'}</option>{members.map(m => <option key={m.id} value={m.id}>{m.name}</option>)}</select></label></> : null}{input.participants.length > 1 ? <AppActionButton onClick={() => setInput(a => ({ ...a, participants: a.participants.filter((_, index) => index !== i) }))}>{zh ? '移除此人' : 'Remove person'}</AppActionButton> : null}</fieldset>)}
    <AppActionButton disabled={input.participants.length >= 30} onClick={() => setInput(a => ({ ...a, participants: [...a.participants, emptyPerson()] }))}>{zh ? '添加家庭成员或访客' : 'Add household member or guest'}</AppActionButton>
    {input.organiserMemberId === me?.id ? <label className="flex min-h-11 items-start gap-3 text-sm"><input className="mt-1" type="checkbox" checked={input.allowSplit} onChange={e => setInput(a => ({ ...a, allowSplit: e.target.checked }))} />{zh ? '我明确同意：名额不足时可部分确认、部分候补。未选则整组同进退。' : 'I explicitly allow partial confirmation and partial waitlisting. Otherwise the household stays together.'}</label> : null}
    {input.channel === 'manual' ? <label className="grid gap-2 text-sm">{zh ? '实际线下办理人姓名' : 'Actual offline organiser name'}<input required maxLength={200} className={inputStyle} value={input.manualOrganiserName} onChange={e => setInput(a => ({ ...a, manualOrganiserName: e.target.value }))} /></label> : null}
    {!input.isInvitation && input.participants.some(p => p.memberId !== me?.id) ? <label className="grid gap-2 text-sm">{zh ? '代办授权依据（谁授权你代填；儿童须明确监护人）' : 'Proxy authority (who authorised this entry; specify guardians for children)'}<textarea required maxLength={2000} className={inputStyle} value={input.proxyAuthorityEvidence} onChange={e => setInput(a => ({ ...a, proxyAuthorityEvidence: e.target.value }))} /><span className="text-xs">{zh ? '代办授权不等于本人同意参加。稍后仍需本人或监护人确认。' : 'Authority to enter information does not provide consent to participate. Personal or guardian consent is still required.'}</span></label> : null}
    <AppActionButton type="submit" variant="primary">{input.isInvitation ? zh ? '保存内部名单' : 'Save internal list' : zh ? '建立报名手续' : 'Start registration procedures'}</AppActionButton>
  </fieldset></form></AppSectionCard>
}

function ApplicationHistory({ eventId, app, currency }: { eventId: string; app: RegistrationApplication; currency: string }) {
  const { me, language } = useAuthStore(), zh = language === 'zh'
  const [open, setOpen] = useState(false), [page, setPage] = useState(1)
  const query = useQuery({ queryKey: ['registration-history', me?.id, eventId, app.id, app.eTag, page], queryFn: () => service.history(eventId, app.id, page), enabled: open, retry: false, gcTime: 0 })
  return <details onToggle={e => setOpen(e.currentTarget.open)} className="rounded-xl border p-3"><summary className="min-h-11 cursor-pointer font-semibold">{zh ? '办理与收退款记录' : 'Procedures and payment history'}</summary>
    <p className="text-xs">{zh ? '录入账号' : 'Entered by'}: {app.createdByMemberId}{app.manualOrganiserName ? ` · ${zh ? '线下办理人' : 'Offline organiser'}: ${app.manualOrganiserName}` : ''}</p>
    {query.error ? <p role="alert">{normalizeApiError(query.error).message}</p> : query.isLoading ? <p role="status">{zh ? '正在读取…' : 'Loading…'}</p> : query.data?.map(row => <div key={row.id} className="border-b py-3 text-sm"><p>{new Date(row.createdUtc).toLocaleString(language)} · {row.operation} {row.amountMinor === null ? '' : fee(row.amountMinor, currency, language)}</p><p className="text-xs">{zh ? '操作账号' : 'Acting account'}: {row.actorMemberId}</p>{row.evidence ? <p className="whitespace-pre-wrap">{row.evidence}</p> : null}</div>)}
    <div className="mt-3 flex gap-2"><AppActionButton disabled={page === 1} onClick={() => setPage(p => p - 1)}>{zh ? '上一页' : 'Previous'}</AppActionButton><AppActionButton disabled={query.data?.length !== 30} onClick={() => setPage(p => p + 1)}>{zh ? '下一页' : 'Next'}</AppActionButton></div>
  </details>
}

function RegistrationWorkspace({ eventId }: { eventId: string }) {
  const { me, language } = useAuthStore(), zh = language === 'zh', cache = useQueryClient(), [params, setParams] = useSearchParams()
  const page = Math.max(1, Number(params.get('page')) || 1), search = params.get('search') || ''
  const applicationId = params.get('application') || undefined
  const query = useQuery({ queryKey: ['registration-work', me?.id, eventId, page, search, applicationId], queryFn: () => service.get(eventId, page, search, applicationId), retry: false, gcTime: 0 })
  const work = query.data, [busy, setBusy] = useState(false), [error, setError] = useState(''), [notice, setNotice] = useState(''), [feeReason, setFeeReason] = useState('')
  const attempt = useRef<{ signature: string; id: string } | null>(null), { requestConfirmation, confirmationModal } = useConfirmation()
  const groupMembers = useQuery({ queryKey: ['registration-members', me?.id, work?.groupId], queryFn: () => groupService.getGroupMemberships(work!.groupId), enabled: Boolean(work?.groupId && me?.memberships.some(m => m.groupId === work.groupId && m.status === 'approved')), gcTime: 0 })
  const members = [{ id: me!.id, name: me!.displayName || (zh ? '本人' : 'Me') }, ...(groupMembers.data || []).filter(m => m.status === 'approved' && m.memberId && m.memberId !== me?.id).map(m => ({ id: m.memberId!, name: m.displayName || (zh ? '成员' : 'Member') }))]
  const refresh = async () => { await cache.invalidateQueries({ queryKey: ['registration-work', me?.id, eventId] }); await cache.invalidateQueries({ queryKey: ['event-work', me?.id] }); await invalidateCurrentTasks(me?.id) }
  const run = async (signature: string, fn: (key: string) => Promise<unknown>, confirm = false) => {
    if (busy || confirm && !await requestConfirmation({ title: zh ? '确认办理操作' : 'Confirm registration action', description: zh ? '此操作会按当前规则记录办理人、时间及处理结果。请核对参加者和所填内容。' : 'This records the actor, time and outcome under the current rules. Check the participant and entered information.', confirmLabel: zh ? '确认' : 'Confirm' })) return
    if (attempt.current?.signature !== signature) attempt.current = { signature, id: crypto.randomUUID() }
    setBusy(true); setError(''); setNotice('')
    try { await fn(attempt.current.id); attempt.current = null; await refresh(); setNotice(zh ? '操作已记录。请查看每人的手续、名额和付款状态。' : 'Action recorded. Check each person’s procedures, place and payment status.') }
    catch (e) { setError(normalizeApiError(e).message); await query.refetch() } finally { setBusy(false) }
  }
  const act: Action = async (app, operation, body = {}, confirm = true) => run(JSON.stringify([app.id, operation, body, app.eTag]), key => service.act(eventId, app, operation, body, key), confirm)
  const changePage = (n: number) => setParams(p => { const next = new URLSearchParams(p); next.set('page', String(n)); return next })
  if (!work) return <AppPageShell title={zh ? '报名工作空间' : 'Registration workspace'}><p role={query.error ? 'alert' : 'status'}>{query.error ? normalizeApiError(query.error).message : zh ? '正在读取…' : 'Loading…'}</p>{query.error ? <AppActionButton onClick={() => void query.refetch()}>{zh ? '重试' : 'Retry'}</AppActionButton> : null}</AppPageShell>
  if (params.get('rules') === '1') return <AppPageShell title={zh ? '报名方案' : 'Registration plan'} backLink={{ to: `/events/${eventId}/work`, label: zh ? '活动工作空间' : 'Event work' }}><EventRegistrationRulesEditor eventId={eventId} /></AppPageShell>
  return <AppPageShell title={work.title[language] || work.title.en || work.title.zh} subtitle={zh ? '报名办理空间' : 'Registration workspace'} backLink={{ to: '/event-work', label: zh ? '我的活动工作' : 'My event work' }}>{confirmationModal}
    {error ? <p role="alert" className="rounded-xl bg-rose-50 p-4 text-sm text-rose-800">{error}</p> : null}{notice ? <p role="status" className="rounded-xl bg-[#e3f0eb] p-4 text-sm">{notice}</p> : null}
    <AppSectionCard title={zh ? '报名状态' : 'Registration status'}><p className="text-sm">{work.publiclyOpen ? zh ? '公开报名已开放' : 'Public registration is open' : work.approved ? zh ? '方案已批准；按邀请或开放时间办理' : 'Plan approved; use an invitation or wait for opening' : zh ? '方案尚未通过审批；只能整理内部名单' : 'Plan not approved; internal lists only'}</p><dl className="mt-4 grid grid-cols-3 gap-3 text-sm">{[['已确认', 'Confirmed', work.confirmed], ['已预留', 'Reserved', work.reserved], ['候补', 'Waitlisted', work.waitlisted]].map(([cn, en, n]) => <div key={String(en)}><dt>{zh ? cn : en}</dt><dd className="mt-1 text-2xl font-semibold">{n}</dd></div>)}</dl>{work.canConfigure ? <Link className="mt-3 inline-flex min-h-11 items-center font-semibold text-[#176b5a]" to={`?rules=1`}>{zh ? '编辑报名规则' : 'Edit registration rules'}</Link> : null}</AppSectionCard>
    {!work.policy ? <p>{zh ? '活动负责人尚未保存报名规则。' : 'The owner has not saved registration rules.'}</p> : <>
      <AppSectionCard title={zh ? '参加规则与办理说明' : 'Rules and registration instructions'}><p className="text-xs">v{work.policy.version} · {zh ? '截止时间' : 'Deadline'} {new Date(work.policy.rules.deadlineUtc).toLocaleString(language)}</p>{(['purpose', 'eligibility', 'terms', 'privacyNotice', 'cancellationTerms', 'paymentInstructions', 'refundTerms'] as const).map((k, i) => <details key={k} open={k === 'terms'} className="mt-3 rounded-xl border p-3"><summary className="min-h-11 cursor-pointer font-semibold">{(zh ? ['报名目的', '资格条件', '参加规则', '隐私说明', '取消条款', '缴费说明', '退款条款'] : ['Purpose', 'Eligibility', 'Participation rules', 'Privacy notice', 'Cancellation', 'Payment', 'Refund terms'])[i]}</summary><p className="whitespace-pre-wrap text-sm">{work.policy!.rules[k]?.[language] || work.policy!.rules[k]?.en || work.policy!.rules[k]?.zh || '—'}</p></details>)}</AppSectionCard>
      {work.policy.rules.feeMinor > 0 && (work.canFinance || work.canApproveFees) ? <AppSectionCard title={zh ? '报名费独立审批' : 'Independent fee approval'}><p className="text-sm">{fee(work.policy.rules.feeMinor, work.policy.rules.currency, language)} · {registrationStatus(work.policy.feeApprovalStatus, zh)}</p><label className="mt-3 grid gap-2 text-sm">{zh ? '审批意见／退回原因' : 'Review comment / return reason'}<textarea className={inputStyle} value={feeReason} maxLength={2000} onChange={e => setFeeReason(e.target.value)} /></label><div className="mt-3 flex flex-wrap gap-2">{(work.canFinance ? ['submit'] : ['approve', 'return']).map(operation => <AppActionButton key={operation} disabled={busy || operation === 'return' && !feeReason.trim()} onClick={() => void run(JSON.stringify([operation, work.policy!.eTag, feeReason]), key => service.fees(eventId, operation, feeReason, work.policy!.eTag, key), true)}>{({ submit: zh ? '提交独立审批' : 'Submit for independent approval', approve: zh ? '批准此版本报名费' : 'Approve this fee version', return: zh ? '退回修改' : 'Return' })[operation]}</AppActionButton>)}</div></AppSectionCard> : null}
      {work.canManage || work.publiclyOpen && work.policy.rules.audience !== 'invited' && work.policy.rules.channel !== 'manual' ? <NewApplication {...{ work, members, busy }} create={input => run(JSON.stringify(input), key => service.create(eventId, input, key), true)} /> : null}
      <label className="grid gap-2 text-sm">{zh ? '按参加者姓名搜索（按办理顺序排列）' : 'Search participant names (queue order)'}<input className={inputStyle} value={search} onChange={e => setParams(p => { const next = new URLSearchParams(p); next.set('search', e.target.value); next.delete('page'); next.delete('application'); return next })} /></label>
      {work.applications.map(app => <AppSectionCard key={app.id} title={app.participants.map(p => p.displayName).join('、')}><div className="space-y-4"><p className="text-sm">{app.allowSplit ? zh ? '办理人已允许拆分名额' : 'Organiser allows split places' : zh ? '整组同进退' : 'Household stays together'}{app.isInvitation ? ` · ${app.invitationMode === 'now' ? zh ? '现在办理确认' : 'Complete now' : zh ? '截止日前办理' : 'Complete by deadline'}` : ''}</p>{app.isInvitation && app.reservationExpiresUtc ? <p className="text-sm">{zh ? '预留到期' : 'Reservation expires'} · {new Date(app.reservationExpiresUtc).toLocaleString(language)}</p> : null}{work.canManage && app.isInvitation && !app.invitedUtc ? <AppActionButton disabled={busy || !work.approved} onClick={() => void act(app, 'send-invitation')}>{zh ? '发送邀请并预留名额' : 'Send invitation and reserve places'}</AppActionButton> : null}
        {app.participants.map(person => <Participant key={person.id} {...{ work, app, person, act, busy, refresh }} />)}
        {app.organiserMemberId === me?.id ? <label className="flex min-h-11 items-start gap-3 text-sm"><input type="checkbox" className="mt-1" disabled={busy} checked={app.allowSplit} onChange={e => void act(app, 'split', { allowSplit: e.target.checked })} />{zh ? '我明确允许部分确认、部分候补' : 'I explicitly allow partial confirmation and waitlisting'}</label> : null}
        {work.canManage || app.organiserMemberId === me?.id ? <div className="flex flex-wrap gap-2"><AppActionButton disabled={busy} onClick={() => void act(app, 'complete')}>{zh ? '完成整组手续' : 'Complete household procedures'}</AppActionButton><AppActionButton disabled={busy} onClick={() => void act(app, 'cancel')}>{zh ? '取消整组报名' : 'Cancel household registration'}</AppActionButton></div> : null}
        <ApplicationHistory eventId={eventId} app={app} currency={work.policy!.rules.currency} />
      </div></AppSectionCard>)}
      {!work.applications.length ? <p className="text-sm">{zh ? '没有符合条件的办理记录。' : 'No matching applications.'}</p> : null}<div className="flex items-center gap-3"><AppActionButton disabled={page <= 1} onClick={() => changePage(page - 1)}>{zh ? '上一页' : 'Previous'}</AppActionButton><span>{page}</span><AppActionButton disabled={!work.hasMore} onClick={() => changePage(page + 1)}>{zh ? '下一页' : 'Next'}</AppActionButton></div>
    </>}
  </AppPageShell>
}
export default function EventRegistrationWorkView() { const { eventId = '' } = useParams(), { me } = useAuthStore(); return <RegistrationWorkspace key={`${me?.id}:${eventId}`} eventId={eventId} /> }
