export const defaultContactLocationStreetAddress = '182 The Runway, Wigram, Christchurch 8042'
export const defaultContactLocationMapUrl = 'https://maps.app.goo.gl/VUdzffqEkKiq2Jy29'
export const defaultContactLocationMapEmbedUrl = 'https://maps.google.com/maps?q=-43.5498482,172.5624243&z=16&output=embed'
export const defaultLocationInquiryContactName = '莊思思'
export const defaultLocationInquiryContactPhone = '027 305 3713'
