const assert = require('node:assert/strict');
const path = require('node:path');
const fs = require('node:fs');
const { showDetailsPane, expandTranslation } = require('./eventDetailsWorkspace.cjs');
const { checkEventTranslation } = require('./eventTranslation.cjs');

async function checkEditorialPreparation({ page, base, language, width, open, errors, detailSaves, acceptedPlans, publishes, setFailure, setViewOnly, setApproved, revisePlan, reads }) {
  const zh = language === 'zh', t = (en, cn) => zh ? cn : en;
  const root = process.env.ALIFE_QA_OUTPUT || 'C:/Data/Alife/Temp/event-preparation-compact-20260922';
  fs.mkdirSync(root, { recursive: true });
  const route = `${base}/groups/qa-group/events/qa-event/workspace?flow=setup&stage=arrangements`;
  const nav = () => page.getByRole('navigation', { name: t('Preparation workspace', '筹备工作区'), exact: true });
  const waitReady = () => page.waitForFunction(() => {
    const button = document.querySelector('.event-editorial-review-action');
    return button && !button.disabled && !button.closest('fieldset:disabled');
  });
  const screenshot = async label => {
    if (label === 'overview') {
      await page.waitForTimeout(500); // Let the initial composition debounce settle before visual capture.
      await waitReady();
      await page.waitForFunction(() => !document.querySelector('[data-arrangement-overview] > [role="status"]')?.textContent?.trim());
    }
    await page.evaluate(() => window.scrollTo(0, 0));
    assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), `${label}: no horizontal page overflow`);
    await page.screenshot({ path: path.join(root, `${label}-${language}-${width}.png`), fullPage: true });
  };
  let releaseLoading;
  const loadingGate = new Promise(resolve => { releaseLoading = resolve; });
  const loadingPattern = '**/api/events/qa-event/preparation/arrangements*';
  const holdArrangements = async request => { await loadingGate; await request.fallback(); };
  await page.route(loadingPattern, holdArrangements);
  await page.goto(route, { waitUntil: 'domcontentloaded' });
  await page.locator('.event-editorial-loading').waitFor();
  assert.equal(await page.locator('.event-editorial-footer').count(), 0, 'initial loading has no empty back-to-top footer');
  await page.evaluate(() => window.scrollTo(0, 0));
  await page.screenshot({ path: path.join(root, `loading-${language}-${width}.png`), fullPage: false });
  releaseLoading();
  await waitReady();
  assert.equal(await page.locator('.event-editorial-stage-nav > *').count(), 4);
  assert.equal(await page.locator('.event-editorial-stage-nav [aria-current]').innerText(), t('Preparation', '筹备'));
  const stageRail = page.locator('.event-editorial-stage-nav');
  assert.equal(await stageRail.evaluate(el => el.scrollWidth > el.clientWidth), false, 'all four stages fit without horizontal scrolling');
  await page.locator('.event-editorial-flow-help summary').click();
  await page.getByText(/Switching stages does not perform|切换阶段不会自动执行/).waitFor();
  await page.locator('.event-editorial-flow-help summary').click();
  await page.locator('.event-editorial-masthead').screenshot({ path: path.join(root, `header-${language}-${width}.png`) });
  assert.equal(await page.locator('.event-editorial-check-count strong').innerText(), '1');
  assert.ok(await nav().getByRole('button', { name: t('Poster', '海报制作'), exact: true }).isDisabled());
  await screenshot('overview');
  const overviewHeight = await page.locator('[data-editorial-overview]').evaluate(el => el.getBoundingClientRect().height);
  assert.ok(overviewHeight < (width >= 1024 ? 600 : 1000), `compact overview height: ${overviewHeight}`);
  if (width >= 1280) assert.ok((await page.locator('.event-editorial-domain').last().boundingBox()).y < 900, 'all related area entries start in the desktop first viewport');
  assert.ok(await page.getByRole('button', { name: t('Save arrangements', '保存活动安排'), exact: true }).isDisabled(), 'unchanged arrangements cannot submit a redundant save');
  const contrast = await page.evaluate(() => {
    const rgb = value => value.match(/[\d.]+/g).slice(0, 3).map(Number);
    const luminance = value => rgb(value).map(v => v / 255).map(v => v <= .04045 ? v / 12.92 : ((v + .055) / 1.055) ** 2.4).reduce((sum, v, index) => sum + v * [.2126, .7152, .0722][index], 0);
    const ratio = (a, b) => { const values = [luminance(a), luminance(b)].sort((x, y) => y - x); return (values[0] + .05) / (values[1] + .05); };
    const samples = [];
    for (const selector of ['.event-editorial-domain > strong', '.event-editorial-domain-state', '.event-editorial-check h2', '.event-editorial-check > p']) {
      const node = document.querySelector(selector);
      samples.push(ratio(getComputedStyle(node).color, getComputedStyle(node.closest('.event-editorial-domain, .event-editorial-check')).backgroundColor));
    }
    const muted = getComputedStyle(document.querySelector('.event-editorial-facts dt')).color;
    samples.push(ratio(muted, 'rgb(255, 254, 250)'), ratio(muted, 'rgb(240, 241, 233)'));
    for (const selector of ['.event-editorial-stage-nav [aria-current]', '.event-editorial-tools [aria-current]']) {
      const style = getComputedStyle(document.querySelector(selector));
      samples.push(ratio(style.color, style.backgroundColor));
    }
    const lockedTool = getComputedStyle(document.querySelector('.event-editorial-tools button:disabled'));
    samples.push(ratio(lockedTool.color, getComputedStyle(document.querySelector('.event-editorial-masthead')).backgroundColor));
    return Math.min(...samples);
  });
  assert.ok(contrast >= 4.5, `normal text contrast ${contrast}`);
  assert.equal(await page.locator('.event-editorial-stage-nav a').nth(1).getAttribute('href'), '/events/qa-event/work?stage=execution');
  await page.locator('[data-arrangement-tile="TEAM.WORK"]').focus();
  await page.keyboard.press('Tab');
  assert.equal(await page.evaluate(() => getComputedStyle(document.activeElement).outlineWidth), '3px');
  assert.ok(await page.locator('.event-editorial-domain').first().evaluate(el => parseFloat(getComputedStyle(el).transitionDuration) <= .001));
  await page.getByRole('button', { name: /Show all modules|显示所有模块/ }).click();
  assert.ok(await page.locator('[data-arrangement-tile="FESTIVAL.OPERATIONS"]').isVisible());
  await page.getByRole('button', { name: /Show related modules|显示相关模块/ }).click();
  assert.equal(await page.locator('[data-arrangement-tile="FESTIVAL.OPERATIONS"]').count(), 0);
  await open('EVENT.DETAILS');
  assert.equal(await page.locator('[data-editorial-overview]:visible').count(), 0, 'editor replaces the overview rather than extending its long page');
  const assertEditorInView = async code => {
    const heading = await page.locator(`[id="module-heading-${code}"]`).boundingBox();
    const savebar = await page.locator('.event-editorial-savebar').boundingBox();
    const back = await page.getByRole('button', { name: t('← Back to preparation overview', '← 返回筹备总览'), exact: true }).boundingBox();
    assert.ok(heading.y >= savebar.y + savebar.height && heading.y < 700, 'editor heading appears immediately, below the sticky savebar');
    assert.ok(back.y >= savebar.y + savebar.height, 'back button must not be covered by the savebar');
    assert.equal(await page.evaluate(() => window.scrollX), 0, 'opening an editor must not pan the whole page sideways');
    assert.ok(savebar.y >= 60 && savebar.y + savebar.height < 900, 'save actions remain in view');
  };
  await assertEditorInView('EVENT.DETAILS');
  await page.screenshot({ path: path.join(root, `editor-${language}-${width}.png`) });
  await nav().getByRole('button', { name: t('Preparation overview', '筹备总览'), exact: true }).click();
  await page.locator('[data-editorial-overview]').waitFor({ state: 'visible' });
  assert.equal(new URL(page.url()).searchParams.has('module'), false, 'overview clears the module bookmark');
  await open('TEAM.WORK');
  await assertEditorInView('TEAM.WORK');
  await page.getByRole('button', { name: t('← Back to preparation overview', '← 返回筹备总览'), exact: true }).click();
  await page.locator('[data-editorial-overview]').waitFor({ state: 'visible' });
  await open('EVENT.DETAILS');
  await showDetailsPane(page, 'form');
  const titleGroup = page.getByRole('group', { name: t('Event title', '活动名称'), exact: true });
  await expandTranslation(titleGroup);
  await checkEventTranslation({ page, group: titleGroup, language, width, root, detailSaves });
  const input = titleGroup.getByLabel('English', { exact: true });
  await input.fill('Editorial draft retained');
  await page.waitForFunction(() => document.querySelector('.event-editorial-review-action')?.disabled);
  assert.equal(detailSaves.length, 0);
  await page.getByRole('link', { name: t('Back to event', '返回活动'), exact: true }).click();
  await page.getByRole('alertdialog').getByRole('button', { name: t('Keep editing', '继续编辑'), exact: true }).click();
  assert.equal(await input.inputValue(), 'Editorial draft retained', 'cancelling leave keeps edits');
  assert.ok(await nav().getByRole('button', { name: t('Formal approval', '正式审批'), exact: true }).isDisabled());
  assert.equal(await page.locator('.event-editorial-stage-nav a').count(), 0, 'stage links cannot silently discard edits');
  await open('TEAM.WORK');
  await assertEditorInView('TEAM.WORK');
  await page.goBack();
  await page.locator('[data-module-editor="EVENT.DETAILS"]').waitFor({ state: 'visible' });
  assert.equal(await input.inputValue(), 'Editorial draft retained', 'history navigation retains the form');
  await page.goForward();
  await page.locator('[data-module-editor="TEAM.WORK"]').waitFor({ state: 'visible' });
  await open('EVENT.DETAILS');
  assert.equal(await input.inputValue(), 'Editorial draft retained');
  const beforeLanguage = reads();
  await page.getByRole('button', { name: t('Select language, current language: English', '选择语言，当前语言：中文'), exact: true }).click();
  await page.getByRole('menuitemradio', { name: zh ? 'English' : '中文', exact: true }).click();
  await page.locator('.event-editorial-header').getByText(zh ? 'Event workspace / Preparation' : '活动工作台 / 筹备', { exact: true }).waitFor();
  assert.equal(await page.locator('[data-module-editor="EVENT.DETAILS"] input[data-locale="en"]').first().inputValue(), 'Editorial draft retained');
  assert.equal(reads(), beforeLanguage, 'language switch must not refetch');
  await page.getByRole('button', { name: zh ? 'Select language, current language: English' : '选择语言，当前语言：中文', exact: true }).click();
  await page.getByRole('menuitemradio', { name: zh ? '中文' : 'English', exact: true }).click();
  await page.locator('.event-editorial-header').getByText(t('Event workspace / Preparation', '活动工作台 / 筹备'), { exact: true }).waitFor();
  setFailure(true);
  await page.evaluate(() => window.dispatchEvent(new Event('focus')));
  await page.getByRole('button', { name: t('Reload preparation status', '重新读取筹备状态'), exact: true }).waitFor();
  assert.equal(await page.locator('[data-editorial-overview]:visible').count(), 0, 'stale data hidden on authorization/read failure');
  setFailure(false);
  await page.getByRole('button', { name: t('Reload preparation status', '重新读取筹备状态'), exact: true }).click();
  await input.waitFor();
  assert.equal(await input.inputValue(), 'Editorial draft retained', 'refresh failure must not destroy drafts');
  await page.getByRole('button', { name: t('Save event details', '保存活动资料'), exact: true }).click();
  await waitReady();
  assert.equal(detailSaves.length, 1);
  assert.equal(detailSaves[0].body.titleEn, 'Editorial draft retained');
  assert.equal(detailSaves[0].body.titleZh, '社区聚餐');
  assert.equal(JSON.parse(detailSaves[0].body.eventDataJson).privateContact, 'preserved');
  await nav().getByRole('button', { name: t('Formal approval', '正式审批'), exact: true }).click();
  await page.waitForURL('**stage=approval');
  await page.getByRole('heading', { name: /This plan requires|本方案采用/ }).waitFor();
  assert.equal(publishes.length, 0, 'opening review does not publish');
  await screenshot('approval');
  await nav().getByRole('button', { name: t('Preparation overview', '筹备总览'), exact: true }).click();
  await waitReady();
  await open('EVENT.DETAILS');
  await input.fill('Concurrent edit retained');
  revisePlan();
  await page.evaluate(() => window.dispatchEvent(new Event('focus')));
  await page.getByRole('alert').filter({ hasText: /saved plan changed|活动方案已更新/ }).waitFor();
  assert.equal(await input.inputValue(), 'Concurrent edit retained');
  assert.ok(await page.getByRole('button', { name: t('Save event details', '保存活动资料'), exact: true }).isDisabled());
  assert.equal(detailSaves.length, 1);
  setViewOnly(true);
  await page.goto(route); await page.locator('[data-editorial-overview]').waitFor();
  await open('EVENT.DETAILS'); await showDetailsPane(page, 'form'); await expandTranslation(titleGroup);
  assert.ok(await input.isDisabled(), 'read-only viewer cannot edit details');
  assert.equal(await titleGroup.getByRole('button', { name: /AI 补全另一语言|AI fill missing language/ }).count(), 0, 'read-only details expose no translation action');
  assert.equal(await page.getByRole('button', { name: t('Save event details', '保存活动资料'), exact: true }).count(), 0);
  setApproved(true);
  await page.goto(route);
  await page.getByRole('button', { name: t('Go to formal approval', '前往正式审批'), exact: true }).waitFor();
  assert.equal(await page.locator('[data-editorial-overview]').count(), 0, 'approved preparation stays frozen');
  await screenshot('frozen');
  assert.equal(acceptedPlans.length, 0, 'no plan mutation from navigation');
  assert.equal(publishes.length, 0);
  assert.deepEqual(errors, []);
  console.log(`PASS editorial ${language}/${width}: layout, contrast ${contrast.toFixed(2)}, explicit save, bilingual draft, recovery, concurrency, read-only and frozen gates`);
}
module.exports = { checkEditorialPreparation };
